### ISSUE TITLE
Response hangs forever with argonaut

### ISSUE THREAD

**Issue by wedens** [http4s/http4s#195] opened 2015-01-21 17:37 UTC
If I have EncodeJson instance that doesn't wrap some value into root object, response will hang forever.
Some error in response is expected.
```scala
case class MyPath(path: String)
implicit def MyPathEncoder: EncodeJson[MyPath] =
    EncodeJson((p: MyPath) => jString(p.path))
...
Ok(MyPath("abc"))
```

**Comment by wedens** [comment] 2015-01-21 18:01
real case is that i have codec for java.nio.files.Path
```
implicit def NioPathCodec: CodecJson[NioPath] =
    CodecJson((p: NioPath) => jString(p.toString), _.as[String].map(Paths.get(_)))
```

**Comment by bryce-anderson** [comment] 2015-01-21 18:04
I think the problem is you're likely throwing an exception with your
```Path``` and the blaze backend isn't closing the connection.

**Comment by bryce-anderson** [comment] 2015-01-21 18:07
@wedens, thanks for the bug report. Please reopen if the problem persists.

**Closed** 2015-01-21 18:07 UTC
