### ISSUE TITLE
org/http4s/blaze/util/package.class is present twice in the classpath

### ISSUE THREAD

**Issue by Unisay** [http4s/http4s#1331] opened 2017-08-22 11:00 UTC
org/http4s/blaze/util/package.class is present twice in the classpath
```
JarClassLoader: Warning: org/http4s/blaze/util/package$.class in lib/http4s-blaze-core_2.12-0.17.0-RC1.jar is hidden by lib/blaze-core_2.12-0.12.6.jar (with different bytecode)
JarClassLoader: Warning: org/http4s/blaze/util/package.class in lib/http4s-blaze-core_2.12-0.17.0-RC1.jar is hidden by lib/blaze-core_2.12-0.12.6.jar (with different bytecode)
```

So that depending on the final classpath order one might get in runtime:
```
java.lang.NoSuchMethodError: org.http4s.blaze.util.package$.End()Lscala/util/Right;  
```

**Comment by rossabaker** [comment] 2017-08-22 12:56
This package object is new in 0.17, so it doesn't affect 0.16.

The problem is that http4s-blaze-core (from the http4s project) and blaze-core (from the blaze project) are both in the same namespace.  We should move all the classes in http4s-blaze-core to a different package.

**Comment by rossabaker** [comment] 2017-08-22 12:57
Even though we haven't caused a clash in 0.16, we probably ought to do the renaming in 0.16 and bubble it up, just to avoid any future problem.  The split package problem has existed for a long time.

**Comment by aeons** [comment] 2017-08-23 08:47
This is fixed now, right?

**Comment by rossabaker** [comment] 2017-08-23 15:00
Yes.

**Closed by rossabaker** 2017-08-23 15:00 UTC
Labels: bug
