### ISSUE TITLE
WebSockets send doesn't work with Stream.awakeEvery

### ISSUE THREAD

**Issue by adamw** [http4s/http4s#3879] opened 2020-11-18 19:35 UTC
Following the example https://github.com/http4s/http4s/blob/main/examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala, a simplified version:

```scala
import cats.effect.{ExitCode, IO, IOApp}
import fs2._
import org.http4s.HttpRoutes
import org.http4s.server.Router
import org.http4s.server.blaze.BlazeServerBuilder
import org.http4s.server.websocket.WebSocketBuilder
import org.http4s.syntax.kleisli._
import org.http4s.websocket.WebSocketFrame
import org.http4s.websocket.WebSocketFrame.Text
import scala.concurrent.ExecutionContext.global

import scala.concurrent.duration.DurationInt

object Test extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    val routes = HttpRoutes.of[IO] { case _ =>
      val toClient: Stream[IO, WebSocketFrame] =
        Stream.awakeEvery[IO](1.seconds).map(d => Text(s"Ping! ${d.toMillis}ms"))
      val fromClient: Pipe[IO, WebSocketFrame, Unit] = _.evalMap {
        case Text(t, _) => IO.delay(println(t))
        case f          => IO.delay(println(s"Unknown type: $f"))
      }
      WebSocketBuilder[IO].build(toClient, fromClient)
    }

    BlazeServerBuilder[IO](global)
      .bindHttp(8080, "localhost")
      .withHttpApp(Router("/test" -> routes).orNotFound)
      .resource
      .use(_ => IO.never)
  }
}
```

which should emit a text frame every second, doesn't do so. I'm connecting using an external client (to eliminate any other problems) and here's what I get during an example run:

```
Ping! 5960ms
Ping! 12371ms
Ping! 22826ms
Ping! 32392ms
Ping! 37357ms
Ping! 40895ms
Ping! 47478ms
Ping! 52800ms
Ping! 56670ms
Ping! 60292ms
Ping! 65057ms
```

The pings are sent, but at intervals significantly larger than 1 second.

I'm using http4s 0.21.9. This happens both locally & on a CI server, although not always.

**Comment by rossabaker** [comment] 2020-11-19 04:34
Hmm.  What client are you using?  Is the client external as in not in the same JVM, or external as in on a remote machine?

Running websocat locally against your example app, I can't reproduce the problem:

```sh
[nix-shell:~]$ uname -or
5.4.67 GNU/Linux

[nix-shell:~]$ websocat --version
websocat 1.6.0

[nix-shell:~]$ websocat ws://127.0.0.1:8080/test
Ping! 1002ms
Ping! 2004ms
Ping! 3005ms
Ping! 4006ms
Ping! 5008ms
Ping! 6009ms
Ping! 7010ms
Ping! 8012ms
Ping! 9013ms
Ping! 10014ms
Ping! 11016ms
Ping! 12017ms
Ping! 13018ms
Ping! 14020ms
Ping! 15021ms
```

**Comment by adamw** [comment] 2020-11-19 06:31
I've tried both sttp+async-http-client and a Chrome plugin with an UI. Also now with websocat:

```
$ websocat ws://127.0.0.1:8080/test
Ping! 4987ms
Ping! 5992ms
Ping! 13921ms
```

**Comment by adamw** [comment] 2020-11-19 06:46
(It does happen *sometimes*. Though now locally it happens almost always, while it used to almost never happen. On travis, it happens almost always, but on GH Actions - we're in the middle of migrating our OSS builds - it has never yet happened. So a fun problem ;) )

**Comment by adamw** [comment] 2020-11-19 07:20
Now I see that even this:

```
import cats.effect.{ExitCode, IO, IOApp}
import fs2._

import scala.concurrent.duration.DurationInt

object Test extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    Stream.awakeEvery[IO](1.seconds).map(d => println(s"Ping! ${d.toMillis}ms")).compile.drain.map(_ => ExitCode.Success)
  }
}
```

exhibits the same problem. The CPU is quite idle. I've tried both java8 & java11. Any hints where to look? :) But I should probably move the issue to fs2.

**Comment by adamw** [comment] 2020-11-19 07:48
Interestingly, after a system restart, this works now locally. Still the failures happen on travis & jenkins quite often.

**Comment by rossabaker** [comment] 2020-11-19 19:03
I'll close this for now, but we can reopen if the eventual resolution from fs2 doesn't help this use case for whatever reason.

**Closed by rossabaker** 2020-11-19 19:03 UTC
