### ISSUE TITLE
Tests should start their own server scaffold

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5230] opened 2021-09-20 15:24 UTC
Was struggling to run `client/test` on main.  Needed to manually start scripts/scaffold_server.js.  We should have our test suites manager their own scaffolds for local development.  I'd completely forgotten this was there until @ChristopherDavenport reminded me.

**Comment by armanbilge** [comment] 2021-09-20 15:30
Yes, sorry about this. The problem is we cannot rely on the test suites' ability to do this because it has a rough translation across JVM/Node.js and no translation for browsers. I think I proposed at some point we build these scaffold servers into the build project itself.

**Comment by armanbilge** [comment] 2021-09-20 15:39
Found it: https://github.com/http4s/http4s/pull/4938#discussion_r683924911

Unless there's any objections I'll try and put that together.

**Comment by armanbilge** [comment] 2021-09-20 16:03
Ok, maybe not. In discord I got some pushback on sbt build-hacking

> We should have our test suites manager their own scaffolds for local development.

If we want to go back to this, then I think we should great-schism the dom modules out of the main repo. It's only browsers where this is a problem, so if we don't have to test on browsers a lot of these hacks will vanish.

**Comment by rossabaker** [comment] 2021-09-20 16:36
I don't understand what's being proposed as "sbt build hacking".

I mostly would like to be able to run `sbt test` and have things just work.  Bonus points if we can drop the Python dependency.  More bonus points if we can write test endpoints in Scala.  I'm currently needing to add one in Node to port what I added in Scala on 0.23.

**Comment by armanbilge** [comment] 2021-09-20 16:40
So, the way these scaffold servers were previously run (and continue so on series/0.22 and 0.23) were as pure-Scala test fixtures as part of the test suites themselves.

This trick didn't work so well after the JS port because (1) it used a JDK server implementation and (2) there's no way a suite running in a browser can start its own server to test against.

My "sbt build hack" proposal is that we implement the scaffold servers in Scala as part of the sbt project. Then, we can start them automatically from within sbt whenever someone runs `test`.

**Comment by rossabaker** [comment] 2021-09-20 17:05
That proposal sounds right to me, though I don't know how people run individual tests.  I mostly use sbt inside my editor, because I still don't understand bloop.

**Comment by armanbilge** [comment] 2021-09-20 17:08
I've asked @ChristopherDavenport and @tpolecat to weigh in b/c at least on discord they didn't seem so crazy about this idea.

**Comment by tpolecat** [comment] 2021-09-20 17:28
I have no opinion, I was just being a wiseass.

**Comment by armanbilge** [comment] 2021-09-22 19:51
Fixed in #5241.

**Closed by armanbilge** 2021-09-22 19:51 UTC
Labels: testing
