### ISSUE TITLE
ConnectException: Connection refused when passing Request or Uri to Client.expect

### ISSUE THREAD

**Issue by TomPoczos** [http4s/http4s#2598] opened 2019-05-26 21:20 UTC
```scala
object Main extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = for {
    x <- BlazeClientBuilder[IO](global).resource.use { client =>
      client.expect[String]("https://www.bbc.com")
    }
    _ <- IO(println(x))

  } yield ExitCode.Success
}
```

The above works while

```scala
object Main extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = for {
    x <- BlazeClientBuilder[IO](global).resource.use { client =>
      client.expect[String](uri = Uri(path = "https://www.bbc.com"))
    }
    _ <- IO(println(x))

  } yield ExitCode.Success
}
```

doesn't. I also tried 

```scala 
client.expect[String](uri = Uri(path = "www.bbc.com", scheme = Option(Scheme.https)))
```

and passing in a Request. In all those cases I'm getting

```
java.net.ConnectException: Connection refused
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
	at java.lang.Thread.run(Thread.java:748)
```

I'm using Debian 9, Scala 2.12, I'll paste my current dependecies below, although I've had this issue for a while and tried multiple other combinations.

```
val http4sVersion = "0.20.1"

libraryDependencies += "org.typelevel" % "cats-core_2.12" % "1.6.0"
libraryDependencies += "org.typelevel" % "cats-effect_2.12" % "1.3.1"
libraryDependencies += "io.circe" % "circe-core_2.12" % "0.11.1"
libraryDependencies += "io.circe" % "circe-generic_2.12" % "0.11.1"
libraryDependencies += "io.circe" % "circe-parser_2.12" % "0.11.1"
libraryDependencies += "io.circe" % "circe-java8_2.12" % "0.11.1"
libraryDependencies += "org.http4s" % "http4s-circe_2.12" % http4sVersion
libraryDependencies += "org.http4s" % "http4s-dsl_2.12" % http4sVersion
libraryDependencies += "org.http4s" % "http4s-blaze-client_2.12" % http4sVersion
```

**Comment by rossabaker** [comment] 2019-05-28 01:02
This is a flaw in our URI class: the URI is a case class with various components, including a scheme (e.g., `http`, `https`), an authority (e.g., `www.bbc.com`), and a path.  When you call `withPath`, it circumvents the parsing done by `fromString`, and the client doesn't know that the URI refers to `www.bbc.com`.

Workaround: if you use `uri"http://www.bbc.com"` (works for String literals), or `Uri.fromString("http://www.bbc.com")` (puts the result in a `ParseResult[Uri]`, so you handle any errors), it should work.

Long term: we're going to replace the URI with something friendlier.

**Comment by TomPoczos** [comment] 2019-05-28 19:29
> Long term: we're going to replace the URI with something friendlier.

Thanks for your reply. I think In the meantime it would help to remove references to the deprecated Uri.uri from the [documentation](https://http4s.org/v0.20/client/). Looking for a better alternative  is what lead me down this path (altough admittedly I should've paid more attention to the docs and also should've realised there is probably a deprecated annotation on Uri.uri with further instructions attached)

**Comment by rossabaker** [comment] 2019-05-29 03:23
It looks to me like tut is configured with fatal warnings and deprecation.  I'm not sure how this slipped through, but point well taken on the docs.  I'll file some followups.

**Comment by rossabaker** [comment] 2019-05-29 03:41
I think the original issue is a duplicate of #2487.

**Closed by rossabaker** 2019-05-29 03:41 UTC
Labels: support
