### ISSUE TITLE
Use better type for path member of Uri class

### ISSUE THREAD

**Issue by jedesah** [http4s/http4s#559] opened 2016-03-15 21:37 UTC
Currently, the `path` member of the `Uri` class is a `String`. I think we can do better than that.

I propose changing the type from `String` to `org.http4s.dsl.Path` (which would probably involve extracting that type definition out of the `dsl` package. Such a change would make it much easier to construct a Uri whose path contain characters that need to be escaped without having to remember to call UrlCodingUtils.urlEncode.

**Comment by rossabaker** [comment] 2016-03-15 21:43
I'm open to that.

On Mar 15, 2016 17:38, "Jean-Rémi Desjardins" <notifications@github.com>
wrote:
>
> Currently, the path member of the Uri class is a String. I think we can
do better than that.
>
> I propose changing the type from String to org.http4s.dsl.Path (which
would probably involve extracting that type definition out of the dsl
package. Such a change would make it much easier to construct a Uri whose
path contain characters that need to be escaped without having to remember
to call UrlCodingUtils.urlEncode.

**Comment by bryce-anderson** [comment] 2016-03-16 00:30
This is a duplicate of #408 and related to #533. We should move the conversation over to #408 and perhaps change the title to be more descriptive.

**Comment by jedesah** [comment] 2016-03-16 16:20
@bryce-anderson My perception was that #408 mostly centered around the encoding behavior of the `/` operator on `Uri` which is somewhat independent than the internal representation but obviously related. I think it's fair to fold this into #408 or keep it separate, I don't have a strong opinion. I created a separate issue because I felt like #408 lacked focus on a single issue.

**Comment by jedesah** [comment] 2016-03-16 16:22
@refried How do you feel about this issue and do you think it can be worked on independently from #533?

**Comment by refried** [comment] 2016-03-16 23:05
@jedesah At a glance I like the idea (keeping the path in a more specific format than String) and think it can be worked independently from #533. :+1:

**Comment by refried** [comment] 2016-03-16 23:11
I would try to be careful to make sure that path is not limited to what can
be expressed by `dsl.Path`, if `dsl.Path` is in some way more specific than
RFC 3986. It's probably fine though :)

**Comment by rossabaker** [comment] 2017-03-01 05:14
I'm generally disgusted with our `Uri` type.  This is a design question to consider as we look to improve that.

**Comment by refried** [comment] 2017-03-01 14:51
I don't mind taking a fresh run at this.  

Can we enumerate the things we don't like?  One of the (arguably tangential) things that had motivated me last time was that I suspected we were missing some subtleties in the different kinds of ways parts of the Uri were url-encoded, and that to the extent that the url-encoding utility methods can be used outside of the Uri class, there was no protection against doubly-encoding a string.  (Other Uri libraries are no better though IMO; for example, Spring will happily url-encode a port number IIRC, which is not a thing.)

**Comment by rossabaker** [comment] 2017-03-01 15:10
* Should we have a more lax `String => Uri` that escapes things?  I have a `.yolo` operator at work primarily for URIs constructed from a host in a config plus a programatic path.  Why do we make this so hard?
* I think last time I looked, some copy constructors on a case class could create invalid URIs despite our attempts to make it so hard to do so from a String.
* Can we interop better with `java.net.URI`?  (They implement two different RFCs.  Is one a subset of the other?)
* A bunch of `with` methods would make manipulation a lot easier.
* The query string DSL doesn't stick with me at all.  I have to relearn it every single time.

**Comment by rossabaker** [comment] 2021-04-05 04:12
@hamnis took care of this, and it's in 0.22.

**Closed by rossabaker** 2021-04-05 04:12 UTC
Labels: RFC
