### ISSUE TITLE
Missing Content-Type in the response after upgrade to 0.18

### ISSUE THREAD

**Issue by jodagm** [http4s/http4s#1557] opened 2017-11-19 17:13 UTC
After upgrading the server from 0.15.11a to 0.18.0-M5 I noticed that Content-Type is not returned

Here is a before and after comparison of the response headers of the same request

 0.15.11a 
```
Content-Type: text/plain; charset=UTF-8
Access-Control-Allow-Headers: Content-Type, *
Vary: Origin,Access-Control-Request-Methods
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: chrome-extension://aejoelaoggembcahagimdiliamlcdmfm
Access-Control-Max-Age: 86400
Date: Sun, 19 Nov 2017 16:20:44 GMT
Content-Length: 393
```

0.18.0-M5
```
Access-Control-Expose-Headers: *
Vary: Origin,Access-Control-Request-Methods
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: chrome-extension://aejoelaoggembcahagimdiliamlcdmfm
Access-Control-Max-Age: 86400
Date: Sun, 19 Nov 2017 16:21:46 GMT
Content-Length: 393
```

```
case req@PUT -> Root / "entities" / entityId as user =>
      req.req.decode[EntityContract] {
        entityUpdate =>
          val futureEvent: Future[String] = RequestExecutor(entityUpdate).execute
          Ok(futureEvent)
      }
```

I also tried to add 
```
     Ok(futureEvent).map(_.putHeaders(`Content-Type`(`text/plain`)))
```

Thank you for your feedback
Jonathan.

**Comment by rossabaker** [comment] 2017-11-19 20:36
This is wrapped in the CORS middleware, right?

**Comment by jodagm** [comment] 2017-11-19 20:39
yes it is, should have mentioned that.

**Comment by rossabaker** [comment] 2017-11-19 21:03
Is it possible to post a sample project that has this behavior?  I tried to reproduce this with a default CORS config around a simple service and can't.  Thanks!

**Comment by jodagm** [comment] 2017-11-19 21:53
Thank you for looking into this. 

comparing server/middleware/CORS between the versions, I see that now the allowed headers is added only if isPreflight=true

I am using a chrome plugin to test the server on localhost and I am not seeing any Preflight going out in that scenario, in that case, threre is no ```Access-Control-Allow-Headers: Content-Type, *``` in response

**Comment by jodagm** [comment] 2017-11-21 20:22
Thank you Oleg,
indeed, I was not using Field.subs (used the web socket example for reference as I am trying to stream the subscription events through websocket)
I will follow the example you sent.

**Comment by jmcardon** [comment] 2017-11-28 04:20
Alright, so after some research in the [W3 CORS spec](https://www.w3.org/TR/cors/#resource-processing-model), as well as [Mozilla Server-side access-control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Server-Side_Access_Control#Preflighted_requests) and [Mozilla CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), there is nothing in the spec that forces `Content-Type` to be present for preflight `OPTIONS` responses, which is what the issue is observing.

`Content-Type` , which the server typically puts for every response, is per w3 typically used to describe the data in the body and is not mandatory. Given preflight responses to `OPTIONS` _do not contain a body_, this header should be inconsequential to the user-agent when processing it.

So then, from where I stand, it's a matter of convention. Do we want to be consistent across http4s versions here or not?.

**Comment by jodagm** [comment] 2017-11-28 12:37
@jmcardon thanks for following up on this.
the issue is that content-type is only returned for OPTIONS response but is missing from the following POST response. 
as a result, some tools we use fail to parse the response

**Comment by jmcardon** [comment] 2017-11-29 03:01
@jodagm like @rossabaker stated, is there a way you could provide a simple dummy project to repro this?

I created a dummy `PUT` service like this:

```scala
 val corsService = CORS(HttpService[IO] {
    case PUT -> Root / "corsy" / name =>
      Ok(s"hi mr $name!")
  })
```

Mounted it on a default server from the g8 template and tested with curl:

```
jose@debbie-ann:~$ curl -H "Origin: http://example.com"   -H "Access-Control-Request-Method: PUT"   -H "Access-Control-Request-Headers: X-Requested-With"  -X PUT --verbose 127.0.0.1:8080/corsy/test
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PUT /corsy/test HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.49.0
> Accept: */*
> Origin: http://example.com
> Access-Control-Request-Method: PUT
> Access-Control-Request-Headers: X-Requested-With
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=UTF-8
< Access-Control-Expose-Headers: *
< Vary: Origin,Access-Control-Request-Methods
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: PUT
< Access-Control-Allow-Origin: http://example.com
< Access-Control-Max-Age: 86400
< Date: Wed, 29 Nov 2017 02:59:14 GMT
< Content-Length: 11
< 
* Connection #0 to host 127.0.0.1 left intact
hi mr test!
```

I can't reproduce this, or see anywhere in the code that this could be a culprit.

**Comment by jodagm** [comment] 2017-12-01 00:25
@jmcardon sorry for the late response

I will try to prepare something that reproduces this

I think the code that may be causing this for me is this:
(from middleware CORS)
```
def corsHeaders(origin: String, acrm: String, isPreflight: Boolean)(
          resp: Response[F]): Response[F] = {
        val methodBasedHeader =
          if (isPreflight)
            config.allowedHeaders.map(headerFromStrings("Access-Control-Allow-Headers", _))
          else config.exposedHeaders.map(headerFromStrings("Access-Control-Expose-Headers", _))
        methodBasedHeader
          .fold(resp)(h => resp.putHeaders(h))
          .putHeaders(
            Header("Vary", "Origin,Access-Control-Request-Methods"),
            Header("Access-Control-Allow-Credentials", config.allowCredentials.toString()),
            Header(
              "Access-Control-Allow-Methods",
              config.allowedMethods.fold(acrm)(_.mkString("", ", ", ""))),
            Header("Access-Control-Allow-Origin", origin),
            Header("Access-Control-Max-Age", config.maxAge.toString)
          )
```
when isPreflight is set, config.allowedHeaders is used
else, exposedHeaders is used

I did confirm that when I force isPreflight to be true for the POST response, I see the expected headers and the response is being processed. 
when I leave isPreflight in false (for the POST response) I see the exposedHeaders instead of the allowedHeaders, which leads to my issue


Thanks,
Jonathan

**Comment by jmcardon** [comment] 2017-12-01 01:53
This doesn't make much sense to me... I mean, `*` over `Content-Type` means all headers are allowed to be exposed. `*` includes `Content-Type`.

[The spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) lists `Content-Type` by default.

> when isPreflight is set, config.allowedHeaders is used
else, exposedHeaders is used

Yes, this is not incorrect. If the request is preflighted, the server _should_ respond with the headers that the CORS service understands. This means, by default responding to an `OPTIONS` request,. which _carries no content_. Thus, it should respond with what headers are allowed by the service.

> when I leave isPreflight in false (for the POST response) I see the exposedHeaders instead of the allowedHeaders, which leads to my issue

POST requests shouldn't have to be preflighted [_unless_ the `Content-Type` of the request itself has a `Content-Type` outside of the default allowed ones](https://www.w3.org/TR/cors/#terminology). Even then, the procedure of preflighting, aka sending the OPTIONS request first, should be done _by the user agent_.

> Edit:
I see in your log that you actually reproduced it :)

No, I didn't. You have to understand that `Access-Control-Allow-Headers` is supposed to be used _for the preflight request itself_. I sent a `PUT` request directly, thus, I didn't go through the OPTIONS route user agents, like browers, are supposed to do for CORS requests, as per the spec.

If you look at the curl request (scroll to the right, I sent `PUT`. Not `OPTIONS`). If I sent OPTIONS, as a user-agent _should_ with cors, I get the following:

```
jose@debbie-ann:~/work/tsec-login$ curl -H "Origin: http://example.com"   -H "Access-Control-Request-Method: PUT" \
>  -H "Access-Control-Request-Headers: X-Requested-With"  -X OPTIONS --verbose 127.0.0.1:8080/corsy/test                                                                                                                                                                 
*   Trying 127.0.0.1...                                                                                                                                                                                                                                                  
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)                                                                                                                                                                                                                      
> OPTIONS /corsy/test HTTP/1.1                                                                                                                                                                                                                                           
> Host: 127.0.0.1:8080                                                                                                                                                                                                                                                   
> User-Agent: curl/7.49.0                                                                                                                                                                                                                                                
> Accept: */*                                                                                                                                                                                                                                                            
> Origin: http://example.com                                                                                                                                                                                                                                             
> Access-Control-Request-Method: PUT
> Access-Control-Request-Headers: X-Requested-With
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Content-Type, *
< Vary: Origin,Access-Control-Request-Methods
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: PUT
< Access-Control-Allow-Origin: http://example.com
< Access-Control-Max-Age: 86400
< Date: Fri, 01 Dec 2017 01:50:04 GMT
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```
Thus the code is right, per the spec.

From where I stand, I _still_ have not been able to reproduce the error. Everything is right per the spec, so please, provide an example of _how you are making your request_ so I may be able to help you.

**Comment by jmcardon** [comment] 2017-12-07 00:22
Any update @jodagm ?

Otherwise, it would be nice if we can close this. I'm not convinced this is an issue vs a misunderstanding of the spec.

**Comment by jodagm** [comment] 2017-12-07 04:50
@jmcardon yes, I understand that though there is a change between the versions, it is still not in contradiction to the spec. The problem is therefore with the tool I am using that does not handle well a response which is in compliance with the spec.

**Comment by jmcardon** [comment] 2017-12-07 19:33
@jodagm not a problem.

Would you consider this closed, or is there any sort of example you can provide so I can further assist this issue?

**Comment by jodagm** [comment] 2017-12-07 19:39
consider this closed.
thanks

**Closed** 2017-12-07 20:48 UTC
