### ISSUE TITLE
CORS middleware block request to the same domain

### ISSUE THREAD

**Issue by PawelJ-PL** [http4s/http4s#2831] opened 2019-08-31 20:57 UTC
It looks, that CORS middleware is blocking request to the same origin. For example:

following request:

```
GET /api HTTP/1.1
Host: 127.0.0.1:8282
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json
Accept-Language: pl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8282/doc/index.html?url=/swagger.yaml&defaultModelsExpandDepth=0
origin: http://127.0.0.1:8282
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

returns:
```
HTTP/1.1 403 Forbidden
Date: Sat, 31 Aug 2019 20:49:17 GMT
Content-Length: 0
```

Maybe I'm wrong, but I think, that request to the same origin (`http://127.0.0.1:8282` in this case) should be always permitted (without additional config).

**Comment by kevinmeredith** [comment] 2019-09-02 02:19
Can you please post code, @PawelJ-PL? I'd like to try to reproduce it.

**Comment by kevinmeredith** [comment] 2019-09-02 02:38
After running `sbt run` on https://github.com/kevinmeredith/http4-cors-issue-2831/tree/one, I then ran `curl`'s:

```
# localhost
$curl -vs localhost:8080/foobar
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /foobar HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=UTF-8
< Date: Mon, 02 Sep 2019 02:33:15 GMT
< Content-Length: 11
< 
* Connection #0 to host localhost left intact
hello world$

# 127.0.0.1
$curl -vs 127.0.0.1:8080/foobar
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /foobar HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=UTF-8
< Date: Mon, 02 Sep 2019 02:33:29 GMT
< Content-Length: 11
< 
* Connection #0 to host 127.0.0.1 left intact
hello world
```

I was not able to reproduce it based on my understanding of the problem. Please let me know, @PawelJ-PL, if I'm missing anything in my test.

**Comment by PawelJ-PL** [comment] 2019-09-02 07:45
It's my mistake. I was thinking, that browser doesn't set `Origin` header in requests to the same domain (only for cross origin requests), but now I've realized, that's not true.
I think You can close the issue and I'm sorry for bothering You

**Comment by kevinmeredith** [comment] 2019-09-02 17:35
It was no bother to me, @PawelJ-PL! I believe you can close it if it's not an issue since you opened it. Or, could you please close, @rossabaker @ChristopherDavenport? Thanks

**Closed** 2019-09-02 17:36 UTC
