### ISSUE TITLE
[Ember client] Much slower performance when body is `Stream.chunk(Chunk.empty)` instead of `Stream.empty`

### ISSUE THREAD

**Issue by Baccata** [http4s/http4s#7539] opened 2024-10-11 07:39 UTC
I'm not certain this qualifies as a bug in http4s or fs2 (or at all), but users have noticed some performance degradation between smithy4s 0.17.x and 0.18.x. After some investigation, it appears http requests end up being created by smithy4s with `fs2.Stream.chunk(Chunk.empty)` as a body (when it was left empty before). 

This means that this [check](https://github.com/http4s/http4s/blob/64a7a1ba84943f82674bdb1bda30a338bab636c3/ember-core/shared/src/main/scala/org/http4s/ember/core/Encoder.scala#L135) ends up being false, and leads to much elevated latency. 

Here's a minimal repro : 

```scala
//> using dep "org.http4s::http4s-core:0.23.28"
//> using dep "org.http4s::http4s-ember-client:0.23.28"

import cats.effect._
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.Request
import org.http4s.Method
import org.http4s.syntax.all._
import fs2.Chunk

object Main extends IOApp.Simple {

  def run: IO[Unit] = EmberClientBuilder.default[IO].build.use { client =>

    // switching to fs2.Stream.empty drastically cuts down latency
    val body = fs2.Stream.chunk(Chunk.empty[Byte])

    def callForever: IO[Unit] = client
      .run(
        Request(Method.POST, uri"https://httpbin.org/post", body = body)
      )
      .use(_.body.compile.drain)
      .timed
      .map(_._1.toMillis)
      .flatMap(IO.println) >> callForever

    callForever

  }

}
```

We're going to protect against this in Smithy4s, but figured it'd be good to raise an issue here, in case the http4s maintainers want to take action.

**Comment by danicheg** [comment] 2024-10-12 13:15
FWIW, that's the case for giving the 1.0 milestone series a chance. Some time ago, we re-engineered the `Entity` model, which now explicitly and straightforwardly handles the case of an [Empty](https://github.com/http4s/http4s/blob/main/core/shared/src/main/scala/org/http4s/Entity.scala#L91) payload.

Returning to the root cause, I don't think we have many options for checking the Stream emptiness. In several places (in http4s, I mean), I've seen checking for structural equality for `fs2.Steam.empty`, so it's kinda expected it started to break with `fs2.Stream.chunk(fs2.Chunk.empty)` as per
```scala
val s1 = fs2.Stream.empty

val s2 = fs2.Stream.chunk(fs2.Chunk.empty)

s1 == s2 // false
s1 == fs2.Stream.empty // true
```

**Comment by Baccata** [comment] 2024-10-12 15:31
I'm not sure it ought to be fixed : I recognise our usecase is niche and I've already got a patch PR'd to the donwstream. 

Maybe fs2 should optimise `Stream.chunk(Chunk.empty)` to return `Stream.empty`, but I'm not certain of the soundness of that.

**Comment by danicheg** [comment] 2024-10-12 15:59
Given the nature of Stream, we can't have a solution that's eligible for every use case without traversing the Stream itself. However, it's ultimately up to our upstream (as well as yours) to address this. Closing here for now. Thanks for reporting, anyway.

**Closed** 2024-10-12 15:59 UTC
