### ISSUE TITLE
Expected `Content-Length: 39` bytes, but only 0 were written.

### ISSUE THREAD

**Issue by dbousamra** [http4s/http4s#710] opened 2016-09-15 05:20 UTC
Copy of stacktrace:

```
ERROR] 2016-09-15 05:12:48,341  org.http4s.blaze.pipeline.Stage fatalError - Fatal Error: Error executing request
java.lang.IllegalStateException: Expected `Content-Length: 39` bytes, but only 0 were written.
        at org.http4s.blaze.util.IdentityWriter.org$http4s$blaze$util$IdentityWriter$$$anonfun$3(IdentityWriter.scala:58)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[ERROR] 2016-09-15 05:12:48,341  org.http4s.blaze.pipeline.Stage outboundCommand - ClientTimeoutStage: Idle: 60 seconds, Request: Duration.Inf received unhandled error command
java.lang.IllegalStateException: Expected `Content-Length: 39` bytes, but only 0 were written.
        at org.http4s.blaze.util.IdentityWriter.org$http4s$blaze$util$IdentityWriter$$$anonfun$3(IdentityWriter.scala:58)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[ERROR] 2016-09-15 05:12:48,341  org.http4s.blaze.pipeline.Stage closeWithError - NIO2 channel closed with an unexpected error
java.lang.IllegalStateException: Expected `Content-Length: 39` bytes, but only 0 were written.
        at org.http4s.blaze.util.IdentityWriter.org$http4s$blaze$util$IdentityWriter$$$anonfun$3(IdentityWriter.scala:58)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Some background. I have a proxy server written in http4s, whose job it is to route requests to downstream services. The code looks like:

``` scala
def makeDownstreamRequest(client: Client, req: Request, service: DownstreamService, path: String, includeQueryParams: Boolean = true): Task[Response] = {

    val serviceUriToUse = req.headers.get(`X-Forwarded-Proto`) match {
      case Some(proto) => proto.value match {
        case "https" => service.serviceUri.https
        case "http"  => service.serviceUri.http
        case _       => service.serviceUri.http
      }
      case None => service.serviceUri.http
    }

    val headers = req.headers.put(service.version)

    val uri = appendPath(serviceUriToUse, path).copy(
      query = req.uri.query,
      fragment = req.uri.fragment
    )

    val newReq = req.copy(
      uri = uri,
      headers = headers
    )
    client.toHttpService.run(newReq).attempt.flatMap {
      case \/-(response) => {
        response.pure[Task]
      }
      case -\/(error)    => {
        BadGateway()
      }
    }
  }
```

This works well normally. But when a request is made that is OAuth 1.0 signed, i receive this stacktrace, BUT only occasionally. It seems to only occur when the server has been idle for a period (say 60s or so). If I load test it, only the first request fails.

I'm using 0.14.3, with a PooledClient with default settings.

**Comment by bryce-anderson** [comment] 2016-09-15 14:22
Very interesting about the oath part. I think you said in the gitter room that this only happens on ec2 instances, is that accurate?

So it looks like the real problem is that somewhere you're writing a body of length 0 that had a content length header that said 39. Could the request that your trying to send downstream be a post request that has gone stale? If you received the head of that request but left the body in the pipeline, and then it timed out, this is the behavior I would expect to see from such a scenario.

**Comment by dbousamra** [comment] 2016-09-15 21:42
I've only ever seen it on EC2 instances yeah. And they are always POST requests.

Hmm, the theory on staleness sounds interesting. I am wondering if the fact that OAuth requests can expire is relevant. I might try playing around with that.

**Comment by bryce-anderson** [comment] 2016-09-16 19:34
I've been wanting to add a 'coalesce the body' filter that automatically collects the whole body of a message. It would be useful in situations like this if you are holding request/response for a bit before using the body by avoiding timeout issues. In theory it could also help by returning client connections, but there are already ways to do about the same thing there.

**Comment by dbousamra** [comment] 2016-09-18 23:29
@bryce-anderson So if I am understanding this correctly, explicitly collecting the whole body via some sort of middleware may help?

**Comment by bryce-anderson** [comment] 2016-09-19 00:00
@dbousamra: only if the problem is that you're seeing a timeout on the request you're attempting to forward.

**Comment by dbousamra** [comment] 2016-09-19 00:15
Hmm. I don't think I am seeing a timeout on the request. I will double check. Any other suggestions? Not being able to debug this locally is painful

**Comment by bryce-anderson** [comment] 2016-09-19 01:02
If you can reliably reproduce the problem, you could map the `Request` body to add some `println` logging to it to see if you're getting a short request or what. It really looks like the body of the `Request` you're trying to forward has timed out so the body hasn't been collected from the source, so when you try to forward it, it has a Content-Length  header that doesn't reflect the actual body. That, or the actual request you're getting is wrong...

Is it possible that you're getting a HEAD request? That could be another reason that a body would be empty but a `Content-Length` header was present. I haven't dug into whether that would cause a problem or not...

**Comment by dbousamra** [comment] 2016-09-19 12:07
So I ran a tcpdump on my EC2 box producing this error, and I can 100% see the request is making its way intact to the box. I can see the Content-Length value matches the length of the POST payload. 

I have come up with some example code that does replicate this issue, though VERY sporadically. 

If you run this, and then start a process hitting the server (I use watch -n 0.1 `"http post http://localhost:8080/whatever payload=123"` , it will produce this error. At one stage I had it reproducing it maybe 30 times within 5 minutes, but since then it's taken me 15m of spamming to produce it. Ideas?

```
object Example extends ServerApp {
  
  val client = PooledHttp1Client()

  val service = HttpService {
    case req @ POST -> Root / "whatever" => {
      val newReq = req.copy(uri = uri("https://httpbin.org/post"))
      client.toHttpService.run(newReq).attempt.flatMap {
        case \/-(response) => response.pure[Task]
        case -\/(error)    => BadGateway()
      }
    }
  }

  override def server(args: List[String]): Task[Server] = {
    BlazeBuilder
      .bindHttp(8080, "0.0.0.0")
      .mountService(service, "/")
      .start
  }
}
```

**Comment by bryce-anderson** [comment] 2016-09-19 14:21
Does this example of bad behavior only work (well, be broken...) on ec2? If
so, what type of instance? Vm image, hardware, etc.

To try to narrow down where the bug lives you could try using different
server and client backends: nio2, jetty-servlet, asynchronous-http-client,
etc.

It still feels like it could be timeout: just because the computer got the
bytes doesn't mean the server didn't run into a timeout in the processing
pipeline. You could try varying the timeout settings or turning them off to
check that hypothesis.

This is definitely an interesting bug.

**Comment by dbousamra** [comment] 2016-09-19 21:40
No. It occurs locally too now. 

I will try with varying server and client backends. I know it happens with both Blaze and Jetty server. I have not tried different clients.

How would I go turning timeouts off? Just:

`BlazeClientConfig.defaultConfig.copy(idleTimeout = Duration.Inf, requestTimeout = Duration.Inf` ?

**Comment by bryce-anderson** [comment] 2016-09-19 22:03
Yes, that is how I would go about configuring timeouts with blaze.

On Mon, Sep 19, 2016 at 2:40 PM, Dominic Bou-Samra <notifications@github.com

**Comment by dbousamra** [comment] 2016-09-19 23:08
I tried with Async-Http-Client 0.14.3:

```
ERROR] 2016-09-20 09:07:09,022  org.http4s.client.asynchttpclient.UnicastSubscriber request - null violated the Reactive Streams rule 3.16 by throwing an exception from request.
java.lang.NullPointerException
	at org.http4s.client.asynchttpclient.UnicastSubscriber.request(UnicastSubscriber.scala:89)
	at org.http4s.client.asynchttpclient.AsyncHttpClient$$anon$2$$anon$1.request(AsyncHttpClient.scala:91)
	at org.http4s.client.asynchttpclient.QueueSubscriber.org$http4s$client$asynchttpclient$QueueSubscriber$$$anonfun$1(QueueSubscriber.scala:19)
	at org.http4s.client.asynchttpclient.QueueSubscriber$$Lambda$120/1853720677.apply$mcV$sp(Unknown Source)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
	at scalaz.concurrent.Task$.Try(Task.scala:387)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
	at scalaz.concurrent.Future.step(Future.scala:109)
	at scalaz.concurrent.Future.listen(Future.scala:75)
	at scalaz.concurrent.Future.runAsync(Future.scala:142)
	at scalaz.concurrent.Task.runAsync(Task.scala:153)
	at org.http4s.blaze.util.ProcessWriter$$anon$1.run(ProcessWriter.scala:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dbousamra** [comment] 2016-09-20 01:19
Alright. So, I am hoping I have worked around it for now. The following code seems to work fine:

object Example extends ServerApp {

  val client = PooledHttp1Client()

  val service = HttpService {
    case req @ POST -> Root / "whatever" => {

      val body = req.body.runLog.run.fold(ByteVector.empty)(_ ++ _)
     
      val newReq = req.copy(uri = uri("https://httpbin.org/post")).withBody(body)

      val withContentType = req.contentType match {
        case Some(ct) => newReq.map(_.putHeaders(ct))
        case None => newReq
      }
      
      withContentType.flatMap { r =>
        client.toHttpService.run(r).attempt.flatMap {
          case \/-(response) => response.pure[Task]
          case -\/(error)    => BadGateway()
        }
      }
    }
  }

  override def server(args: List[String]): Task[Server] = {
    BlazeBuilder
      .bindHttp(8080, "0.0.0.0")
      .mountService(service, "/")
      .start
  }
}

**Comment by rossabaker** [comment] 2016-09-20 03:03
That async-http-client error is something I've heard reports of before, but haven't seen myself.  I'm spinning that off as a separate issue.  Hopefully your work will help me reproduce it.

**Comment by bryce-anderson** [comment] 2016-09-20 05:07
@dbousamra you're so close to my 'coalesce the body filter' I can taste it! Just a couple quick notes: you shouldn't need to check the content-type: that header should still be on the copy of the request if you can just turn that body into a `Process[Task, ByteVector]` using `Process.eval(Task[ByteVector])` and set it the same time you change the `Url`. Of course if you're not getting the right sized body, the content-length header will be incorrect. Of course this would all be much cleaner as a middleware.

I'm curious what type of EC2 instance you're using when this freeze up. If its a small instance there is a chance you're running into a deadlock on a thread pool of size 1. And did you try setting the timeouts to something different? `Inf` would be a good one to try.

**Comment by dbousamra** [comment] 2016-09-20 06:12
@bryce-anderson Ha. What a saga.

Good point on just setting the body like that. I found if I use withBody, it set the content-type to application/octet-stream because of the ByteVector.

I upgraded to 0.0.15-SNAPSHOT on a whim, to see if this issue might have been subtly fixed somehow. It was a bit of a brute-force move I didn't expect to work, but low and behold, I'm no longer seeing issues. Perhaps we can bisect to figure it out.

I am using a t2.small (so single VCPU/core) right now. Why would I run into a deadlock with size 1 thread pool? Which thread pool is this also?

**Comment by dbousamra** [comment] 2016-09-21 08:11
@bryce-anderson Upping the size of the thread pool from 1 to 10 seems to have fixed my dead lock issue. Will update as I find out more.

**Comment by bryce-anderson** [comment] 2016-09-21 16:36
That's good news about the deadlock issue! It's not clear to me what the stack trace you posted relates to. What conditions is that under?

And I still wonder what would happen if you set all timeouts to `Inf`.

**Comment by dbousamra** [comment] 2016-09-21 22:14
The stacktrace I posted is the result of the same code (the pseudo 'coalesce body filter') using V0.15.0-SNAPSHOT. I'm not sure what changed between 0.14.3 and that. 

Duration Inf did not seem to make a difference sorry :(

**Comment by rossabaker** [comment] 2018-03-26 16:50
Closing due to idleness and old version.  Please reopen if it's still a problem.

**Closed by rossabaker** 2018-03-26 16:50 UTC
Labels: bug
