### ISSUE TITLE
Empty body with async-http-client

### ISSUE THREAD

**Issue by peterneyens** [http4s/http4s#3293] opened 2020-04-02 15:57 UTC
After upgrading to `0.21.2` I am seeing a lot of empty body errors while using async-http-client as the client backend.

```
Caused by: org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON: empty body
	at org.http4s.jawn.JawnInstances$.defaultJawnEmptyBodyMessage(JawnInstances.scala:42)
	at org.http4s.jawn.JawnInstances.jawnEmptyBodyMessage(JawnInstances.scala:17)
	at org.http4s.jawn.JawnInstances.jawnEmptyBodyMessage$(JawnInstances.scala:16)
	at org.http4s.circe.package$.jawnEmptyBodyMessage(package.scala:3)
	at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderByteBufferImpl$1(CirceInstances.scala:41)
	at scala.util.Either.flatMap(Either.scala:352)
	at cats.data.EitherT.$anonfun$subflatMap$1(EitherT.scala:365)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at cats.effect.IO$Map.apply(IO.scala:1504)
	at cats.effect.IO$Map.apply(IO.scala:1502)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:142)
```

I suspect that something in #3261 causes the body to be emptied before it is read in some cases?

**Comment by rossabaker** [comment] 2020-04-03 03:42
@djspiewak, are you seeing anything of the sort?  I think you're one of the heavier users of the AHC backend.

**Comment by rossabaker** [comment] 2020-04-03 05:55
CI failure [looks related](https://github.com/http4s/http4s/runs/556941825#step:10:3006)?

**Comment by djspiewak** [comment] 2020-04-03 20:52
> are you seeing anything of the sort?

Hmm, definitely not. I'm also a bit surprised by OP. Nothing in the change I made seems to be capable of causing a body to be *emptied* unless you mess up the `Resource` somehow. Like, for example, if you take the request `Resource` and just `use(IO.pure(_))` on it, and *then* read the `body`, you must definitely will see emptiness. But if you're doing that, then your code is broken, and was only working before because the outer `Resource` was not correctly closing anything.

**Comment by djspiewak** [comment] 2020-04-03 20:53
Also @rossabaker that CI failure *does* look related, at least at first glance. What I'd be really curious to see is if the test suite is correctly keeping `body`-reading within the `Resource` scope, or if it's applying `use` incorrectly.

**Comment by rossabaker** [comment] 2020-04-04 04:16
Nope, it's a very boring test:

```scala
       "POST a normal body" in {
          val uri = Uri.fromString(s"http://${address.getHostName}:${address.getPort}/echo").yolo
          val req = POST("This is normal.", uri)
          val body = client.expect[String](req)
          body must returnValue("This is normal.")
        }
```

I don't recall ever seeing it fail before this PR, and it's failing often (but not reliably) now.

**Comment by djspiewak** [comment] 2020-04-05 05:52
What's the definition of `returnValue`?

**Comment by rossabaker** [comment] 2020-04-05 14:55
An ancient helper adapted from Specs2's `Task` support.  Roughly translates to `body.unsafeRunTimed(timeout) must_== ("This is normal.")`.

**Comment by djspiewak** [comment] 2020-04-06 15:01
If that's all it is… I really don't understand how it would fail like this.

**Comment by caoilte** [comment] 2020-04-07 11:28
Just to add. We've been seeing this for a couple of weeks in three separate Microservices. I only just tracked it down today to being this issue. Services that are absolutely fine running at scale on `0.21.1` start to return intermittent empty body responses on `0.21.2`.

**Comment by djspiewak** [comment] 2020-04-07 18:04
I think it's fair to say this is a real legit thing. I'm happy to throw in as much time as I can to track it down, since it seems very likely that my change introduced it. :-/

**For anyone who is experiencing this issue…** If you can give me as much information as possible about what's going on, it'll help a lot:

- How are you sequencing the body and the request? Particularly, are you using `.compile.resource` on the body? Are you doing some streamy things on the body within the outer `Resource`? Are you just `use`ing them all down to `IO`?
- Have you done an `lsof` to see what the sockets are doing as this is happening?
- It's intermittently happening, so roughly what percentage are you seeing?
- What kind of body are you looking at?

Also thinking about this, I *may* have an idea of what could be causing this. I'll fiddle around with a branch on it as soon as I can. More information is really helpful though.

**Comment by vvlevykin** [comment] 2020-04-09 11:44
This problem doesn't occur when using jdk http client, it happens only with async-http-client in our case.
* We are using `expect`, not `.compile.resource`.
* About 1 in 5 requests fail, it seems.

**Comment by wemrysi** [comment] 2020-04-12 19:19
@djspiewak There appears to be a race-condition between when the async callback is [called from `onStream`](https://github.com/http4s/http4s/blob/v0.21.3/async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala#L99) and when it is [called from `onCompleted`](https://github.com/http4s/http4s/blob/v0.21.3/async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala#L126).

If `onCompleted` is invoked before the callback invocation from `onStream`, the `Response` passed to the callback will have an empty body, if `onStream` wins it will have the subscriber-backed body.

**Comment by djspiewak** [comment] 2020-04-13 14:54
@wemrysi That's exactly what I'm thinking as well. What I'm pondering right now is the best way to correct this. In theory, a body-less response will *never* invoke `onStream` (according to the AHC docs anyway), so it feels like we have to have something in `onCompleted`. I can't see a way around creating yet another `Ref` to manage this fiddly bit of state. :-/

**Comment by kevinmeredith** [comment] 2020-04-19 04:34
Re: https://github.com/http4s/http4s/issues/3293#issuecomment-612663360, @wemrysi, are you able to add a test (even if it's pseudo-code) explaining how to reproduce it? I know you mentioned it's a race condition, but I'm asking for my own understanding. Thanks

**Comment by wemrysi** [comment] 2020-04-19 19:09
@kevinmeredith I don't have a test that reliably reproduces this, though existing tests in the http4s suite are failing intermittently due to the problem.

Here's an example of a scenario that would trigger the problem
1. An HTTP message with a small entity body is received.
2. `onStream` is called
3. The callback invocation in `onStream` is forked and started, `onStream` completes because `runAsync`
4. async-http-client processes the entity body
5. `onCompleted` is called prior to the async callback from (3) completing, which completes the callback with response having an empty body
6. The async callback from (3) completes, having no effect because of (5)

it comes down to whether the forked callback from (3) runs before `onCompleted` is called.

**Closed** 2020-04-23 02:25 UTC
Labels: bug
