### ISSUE TITLE
HTTP/2 response bodies (strict) bigger than 16KiB are not being sent with Ember

### ISSUE THREAD

**Issue by janilcgarcia** [http4s/http4s#6844] opened 2022-12-03 21:17 UTC
As I pointed out in #6842, there seems to a problem with ember when responding with bodies longer than 16KiB. I was able to isolate the issue and it seems to be related exclusively with HTTP/2.

This is a scala-cli file you can use to replicate it:
```scala
//> using scala "3.2.0"
//> using lib "org.typelevel::cats-effect:3.4.2"
//> using lib "co.fs2::fs2-core:3.4.0"
//> using lib "co.fs2::fs2-io:3.4.0"
//> using lib "org.http4s::http4s-dsl:1.0.0-M37"
//> using lib "org.http4s::http4s-ember-server:1.0.0-M37"
//> using lib "org.slf4j:slf4j-simple:2.0.5"

import cats.syntax.all.*
import cats.effect.{Async, ExitCode, IO, IOApp, Resource}
import cats.effect.syntax.all.*
import org.http4s.HttpRoutes
import org.http4s.MediaType
import org.http4s.headers.`Content-Type`
import org.http4s.dsl.Http4sDsl
import org.http4s.ember.server.EmberServerBuilder
import com.comcast.ip4s.port

object RunServer extends IOApp with Http4sDsl[IO]:
  private val app = HttpRoutes.of[IO] {
    case GET -> Root / "bytes" / IntVar(numberOfBytes) =>
      val bytes = Array.fill(numberOfBytes)('A'.toByte)

      Ok(bytes).map(_.withContentType(`Content-Type`(MediaType.text.plain)))
  }.orNotFound

  private val server =
    EmberServerBuilder
      .default[IO]
      .withHttpApp(app)
      .withHttp2
      .withPort(port"5000")
      .build

  override def run(args: List[String]): IO[ExitCode] =
    server.useForever
```
I also uploaded an SBT project where you can check how it behaves with(out) TLS and HTTP/2 in separate services (https://github.com/janilcgarcia/http4s-bug).

Using curl:
```bash
curl --http2 localhost:5000/bytes/16384
# result is fine, you get the entire body
curl --http1.1 localhost:5000/bytes/16384
# same

curl --http2 localhost:5000/bytes/16385
# Get headers but no body,
# curl: (18) transfer closed with 16385 bytes remaining to read

curl --http1.1 localhost:5000/bytes/16385
# works ok as well
```

Libraries/Scala versions are up there. I'll try to test it ember-server built from source later.

I would love to hlep, but I'd need some pointers to where to look for this bug, I never implemented anything related to an HTTP server before.

I'm on Debian 11 with OpenJDK 17 from the repository, but the same issue happens on Fedora 37 with their OpenJDK 17

**Comment by armanbilge** [comment] 2022-12-03 21:19
Thanks for the excellent reproduction! If you are eager to dig in the H2 sources are here:
https://github.com/http4s/http4s/tree/series/0.23/ember-core/shared/src/main/scala/org/http4s/ember/core/h2

**Comment by armanbilge** [comment] 2022-12-03 21:24
Can you replicate the issue with http4s 0.23.x? It might be an issue due to changes in the 1.x branch.

**Comment by janilcgarcia** [comment] 2022-12-03 21:34
Yes, same issue with 0.23.16.

**Comment by armanbilge** [comment] 2022-12-03 21:42
One more clue is that this bug relates to the maximum frame size used for H2.
https://github.com/http4s/http4s/blob/bbf975115774c6dae7e3de4fc1fbe7b881c8b942/ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Frame.scala#L529

**Comment by janilcgarcia** [comment] 2022-12-03 22:27
I'm having trouble finding some point `maxFrameSize` is being used to split the messages, it seems to be used for incoming messages.

On `H2Stream.sendData` there seems to be a split based on `H2Stream.State.windowSize`, which varies through out time.

What are trailers, BTW?

**Comment by janilcgarcia** [comment] 2022-12-03 23:24
So, I found a veeeryyy hacky work-around, and I have a good hypothesis on how it works, it's this mess right here:
I renamed `sendData` on `H2Stream` to sendData1 and replaced by this:
```scala
  def sendData(bv: ByteVector, endStream: Boolean): F[Unit] = {
    val maxSize = 16 << 10
    if (bv.size > maxSize)
      sendData1(bv.take(maxSize), false) >> sendData(bv.drop(maxSize), endStream)
    else
      sendData1(bv, endStream)
  }
```

I know this is absurdly inefficient, but it proves one thing: send Data frames larger than 16KiB seems to be what's causing the issue (Yaay). Now, I think the reason for that is that the CLIENT won't accept bigger frames. In the [RFC](https://www.rfc-editor.org/rfc/rfc7540#section-4.2l) it says we should use a max frame size given by the receiver, I assume all clients I used, use 16KiB max size.

It looks like ember already gather that setting, I'm trying to find where. I also don't know precisely where to do the split. I tried on H2Connection but it didn't work. At H2Stream is obviously bad.

**Comment by janilcgarcia** [comment] 2022-12-03 23:54
I'm making a pull request!

**Comment by armanbilge** [comment] 2022-12-03 23:59
@janilcgarcia awesome! Would you mind targeting your PR to the `series/0.23` branch? Thanks!

**Comment by janilcgarcia** [comment] 2022-12-04 00:03
@armanbilge no problem

**Comment by valencik** [comment] 2023-01-16 14:19
Fixed in https://github.com/http4s/http4s/pull/6882

**Closed by valencik** 2023-01-16 14:19 UTC
Labels: bug, module:ember-server
