### ISSUE TITLE
Flaky test: Preserve body with a known URI

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2851] opened 2019-09-09 18:22 UTC
```
[error]   x preserve body with a known uri (5 seconds, 876 ms)
[error]    Falsified after 43 passed tests.
[error]    > ARG_0: Request(method=REPORT, uri=http://%E7%95%96%E3%A2%9C%EA%B8%B8%EC%81%9F:%E7%B7%A1%EE%A3%B3%E1%99%A0%E6%9D%B5%EA%AD%AD%E1%AE%A8%EC%BA%AA@'**%614%B8!*&;%2C$%72'*:10?%EB%B4%96%E5%8E%90%EE%99%81%E5%9B%87%E6%A1%A9%E0%A1%90%E9%8E%A7%E1%A5%A3=%E1%A5%BB%E2%89%B4%EC%94%9B%E7%B2%87%E8%90%80%E7%94%AD%E8%AC%AB%E1%84%8E%E9%AF%9B%EA%8E%9C&foo=bar&%E8%B6%A0%E6%B4%B6%E6%BD%A8%E8%BD%86%EE%9D%88%EF%85%A9%E7%8A%B6%E5%B0%A0%E7%8D%9A%EA%9D%A3%EF%87%B4%E7%A1%93%EA%AF%8D%E9%9F%9F%E4%B7%82%E4%B7%9E%EE%A1%B2%E3%9B%B0%E4%BA%BD%E7%8E%95%E9%95%B2%EC%99%BF=%E4%AF%98%E2%A0%86%E6%96%83%E5%86%84%E0%AE%98%E2%AC%9C%EB%AD%98%EC%8B%B9%E4%9B%B5%E9%AF%BF%EF%B4%90%EA%81%A3%EA%98%8B%E1%8C%AA%E8%9E%BF%E8%B6%A4%E4%B7%A9#_/??, headers=Headers(Content-Length: 7857931302874446567, Accept-Charset: ISO-8859-3;q=0.75, ISO-8859-9;q=0, IBM1047;q=0, IBM284;q=0.017, Big5;q=0.521, UTF-16, IBM500;q=0.828, IBM852, *;q=0.085, ISO-8859-1;q=0, x-IBM737;q=0, IBM865, x-IBM922;q=0, Content-Length: 7641536522322961043, Accept-Charset: x-IBM1381;q=0.667, GB18030;q=0, windows-1252, x-IBM1123, UTF-32;q=0, x-MacCroatian;q=0, x-JIS0208;q=0.125, IBM01143;q=0, x-euc-jp-linux, x-IBM1097;q=0.528, *, x-eucJP-Open, x-MacArabic;q=0, X-UTF-32BE-BOM;q=0, KOI8-U;q=0, GBK;q=0.442, Accept-Charset: ISO-2022-JP;q=0, IBM01145, IBM277;q=0, x-IBM1381, GB2312;q=0.33, ISO-8859-3;q=0, x-windows-874;q=0.194, IBM00858;q=0.167, UTF-16LE, IBM855;q=0, x-IBM948;q=0, x-SJIS_0213, TIS-620, EUC-JP;q=0, Big5;q=0, x-IBM933, US-ASCII;q=0.643, IBM869;q=0, x-windows-949;q=0.503, windows-1256, x-IBM1006;q=0, IBM870, x-euc-jp-linux;q=0, x-IBM1097, *;q=0.905, x-IBM921;q=0, UTF-32BE, x-windows-50221;q=0.61, IBM285;q=0, x-COMPOUND_TEXT;q=0, KOI8-U;q=0, IBM01140;q=0, IBM01148;q=0.096, Allow: UNBIND, CHECKOUT, zi&0HgFh6NTu`Hli*8a+O+_fd0kJt9z0L5qF|GZ-H, UNCHECKOUT, MKACTIVITY, CHECKIN, MKCOL, LABEL, HEAD, Accept-Charset: IBM01146;q=0.474, GB18030, X-UTF-32LE-BOM, IBM278;q=0.95, ISO-8859-2;q=0, x-IBM942, IBM284, ISO-8859-7;q=0.514, US-ASCII;q=0, x-EUC-TW;q=0, IBM01144;q=0.487, x-Big5-HKSCS-2001;q=0.248, *;q=0.193, x-IBM875;q=0, IBM285, x-MacTurkish;q=0.124, x-PCK;q=0.251, x-IBM1025;q=0, IBM037;q=0.149, ISO-8859-5;q=0.356, IBM01148;q=0, Accept-Charset: IBM01146, x-IBM949;q=0.903, ISO-2022-KR, windows-1252, IBM855;q=0.797, IBM866, x-Big5-Solaris, KOI8-R;q=0.437, US-ASCII, x-windows-950, *;q=0, UTF-32BE, Date: Fri, 26 Nov 4962 00:55:48 GMT, Accept-Charset: x-MS950-HKSCS-XP;q=0.194, IBM860, IBM290, IBM864, x-EUC-TW, x-IBM949C, JIS_X0212-1990, EUC-KR;q=0, *, x-MacHebrew;q=0.456, IBM297;q=0.295))
[error]    > ARG_1: "﻿"
[error]    > ARG_1_ORIGINAL: "﻿엂斁"
[error]    The seed is vo8ZKXqNtcquwE2AX_Wstuipz3QSEPvlDW-XrFugayL=
[error]    
[error]    > '' != '﻿' (TraversalSpec.scala:60)
```

**Comment by bfdes** [comment] 2019-11-11 07:23
Duplicate of #2794 ?

**Comment by m-sp** [comment] 2021-02-23 17:43
yep indeed a duplicate

**Closed by m-sp** 2021-02-23 17:43 UTC
