### ISSUE TITLE
Document GraalVM

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3299] opened 2020-04-03 05:58 UTC
There is increasing interest in GraalVM.  We should document its usage and pitfalls.

One pitfall found in #3288 is that segfaults happen with `--static`.

**Comment by drocsid** [comment] 2020-04-09 07:22
@rossabaker I have a bit of experience with graal and also building images. Would you like me to give it a shot. Also running http4s static images at http://860weather.bar/

**Comment by rossabaker** [comment] 2020-04-13 03:46
@drocsid That would be wonderful!  If that project is open source, we could also link to it so people have a real-world example of Graal usage.

**Comment by rossabaker** [comment] 2020-04-15 13:22
A nice tip from @JamesCosford worth mentioning:

> Just ran into this issue: oracle/graal#1631 -- alpine linux doesn't include glibc, so dns requests from graalvm native images don't work properly, but fail with java.nio.channels.UnresolvedAddressException via blaze. Solved by pulling in a version of alpine with glibc included (https://hub.docker.com/r/frolvlad/alpine-glibc). Posting here in case it can save someone else half a day of head scratching.

**Comment by drocsid** [comment] 2020-04-16 07:06
Yes that was already linked to via #3288 via https://github.com/oracle/graal/issues/2309 and following up on https://github.com/gradinac/musl-bundle-example/pull/1 . Wanting to get back to this.

**Comment by jamescosford** [comment] 2020-04-16 07:16
I think those are separate issues.

I also had trouble using logback-classic for logging straight out of the box, which I forgot to document at the time. It is possible that with some additional configuration it might have worked, but I didn't have time so I just changed to using JUL.

**Comment by drocsid** [comment] 2020-04-16 07:37
Ahh I see that now. I used glibc from debian distro itself as mentioned inhttps://github.com/gradinac/musl-bundle-example/pull/1 . However I am getting protocol exceptions via IPv6 as also mentioned there. Then I'm currently running two native images for  http://860weather.bar/ . The IPv4 service is a static image. The IPv6 is not due to the protocol exception. However it runs without --static.

**Comment by drocsid** [comment] 2020-04-16 07:55
The DNS exceptions were resolved for me on #3288 and https://github.com/gradinac/musl-bundle-example/pull/1. I used muslc . The solution on pull 1 was taken from advice on
https://github.com/oracle/graal/issues/1919#issuecomment-589085506


I don't believe I had issues logging. Will follow up with some example repo and maybe we can discuss muslc vs glibc + muslc approach...

**Comment by jamescosford** [comment] 2020-04-16 09:05
Also I found it super useful in the beginning the instruction to use sbt-assembly plugin to build a fat-jar, so you can just pass that single jar to native-image.

I am using building my native-images in a docker container built with this Dockerfile
```
FROM oracle/graalvm-ce:latest
WORKDIR /opt/graalvm
RUN gu install native-image
ENTRYPOINT ["native-image"]
```

invoked with

```
  docker run\
    --memory 12GB\
    --cpus 4\
    --rm -it\
    -v "$FAT_JAR_CP":"/opt/cp"\
    -v "$BUNDLE_DIR":"/opt/graalvm"\
    graalvm-native-image\
        -jar /opt/cp/$FAT_JAR_NAME\
        --static\
        --no-server\
        -H:Name=graalni\
        --no-fallback\
        --allow-incomplete-classpath\
        --report-unsupported-elements-at-runtime
```

**Comment by drocsid** [comment] 2020-04-16 19:53
Yes, building an `uber jar` is necessary for using graal.... Regarding docker I feel it's probably necessary if you work on a mac, making it more portable. Also good for production. I'm a hack so I didn't do that.

**Comment by drocsid** [comment] 2020-04-16 20:24
I'm going to create reproduction for issues E.G. IPv6 on https://github.com/drocsid/https_example . This is based on the gitter8 template. Then I suggest after resolving this we might create an example based on the shipping gitter8 example....

**Comment by jamescosford** [comment] 2020-04-17 06:01
Building an uber jar is not technically necessary, it just makes life much easier by ensuring all your dependencies are in the same place. You COULD write out all of your dependency jar locations in the native-image classpath argument if you wanted to.

Docker is an easy option if you want to be able to easily run your product on different platforms, since native-image builds a binary which can only run on same system/architecture as the one it is built on. Graal native-image doesn't offer cross-compilation yet. My work machine is a macbook, and my deployment environment is AWS Amazon Linux 2, so it was necessary to build for linux.

Not doing unnecessary work doesn't make you a hack! It makes you pragmatic ;)

**Comment by drocsid** [comment] 2020-04-17 06:44
I followed up regarding the ipv6 issue I'm having with the static image: https://github.com/gradinac/musl-bundle-example/pull/1#issuecomment-615070966

You can also see what I'm doing to build static images there: 
https://github.com/drocsid/https_example . 

If you change the blaze server to IPV4 address the native image build should work fine. Regarding documentation. My example is based off the gitter8 template. Then can we just provide an example there? Maybe add script and sbt-assembly to the template?

Finally I suggest we add a deployment section to the http4s documentation.

@jamescosford @rossabaker what do you guys think?

**Comment by LeifW** [comment] 2020-04-17 09:23
@noelwelsh did a blog post on running http4s under GraalVM:
https://www.inner-product.com/posts/serverless-scala-services-with-graalvm/

**Comment by jamescosford** [comment] 2020-04-17 09:40
Wish I had seen that blog post... I ended up rolling everything back to scala 2.12 when I hit that issue.

**Comment by drocsid** [comment] 2020-04-17 10:05
While the blog post from @noelwelsh is attractive and informative; it somewhat obfuscates the native image build commands via the native image sbt plugin. 

That plugin doesn't have very much documentation. https://www.scala-sbt.org/sbt-native-packager/formats/graalvm-native-image.html

Finally it was not building a truly static image using muslC, then using linked components. Then one would have segmentation faults using the options in those directions as on #3288.

**Comment by drocsid** [comment] 2020-04-17 10:05
In response to @LeifW ^^

**Comment by drocsid** [comment] 2020-04-17 10:07
And I'm fine stepping away with my opinions if you prefer to just point at that example.

**Comment by jamescosford** [comment] 2020-04-17 10:23
@drocsid I think your idea of writing some targeted docs has great value. It feels like there are a few useful resources around, but they all have shortcomings or miss some critical points.

**Comment by noelwelsh** [comment] 2020-04-17 10:45
I think it would be very valuable to have canonical documentation on building http4s w/ Graal.  The `muslc` issues and fixes are something I haven't had to deal with yet, so having them documented somewhere would be fantastic.

Regarding my blog post, I think you misread it. The `native-image` command is given in the post:

```
native-image --verbose -jar target/scala-2.13/http4s-native-image-assembly-0.1.0-SNAPSHOT.jar ping-server
```

I don't use `sbt-native-packager`. IIRC I couldn't get it to work. I wrote my own sbt tasks, which are also given in the blog post.

**Comment by drocsid** [comment] 2020-04-17 11:38
@noelwelsh sorry if I misread, actually went looking in the source tree and not sure where I got that `sbt-native-packer` from...

Here's some information regarding the command string I built bringing http://860weather.bar up.

https://github.com/drocsid/https_example/blob/master/native-image-build-cmd.sh

Adding `UseMuslC` to fix segfaults and build a true static image that doesn't depend on linked libraries. Add `initialize at build time` can be read from the graal docs. Again we lose performance if we instead do this at runtime.

Enable `http`, `https`, `enable security services` all seem to be required if you do anything non trivial with `http` / `https`.

`native-image --initialize-at-build-time --static -H:UseMuslC="$PWD/muslC/bundle" --enable-http --enable-https --enable-all-security-services --verbose -jar ./target/scala-2.13/weatherdemo-assembly-0.0.1-SNAPSHOT.jar nativeImage`

**Comment by rossabaker** [comment] 2020-04-18 15:49
Yes, I strongly agree with Noel that we should have canonical documentation.  We're seeing a large uptick in GraalVM interest, and having a well-maintained page for it will be helpful to new users, vs. blog posts that need to be Googled and probably won't be updated with subsequent insights.

**Comment by drocsid** [comment] 2020-04-18 20:53
I made specific questions unanswered. But I spend some time building up a command that will actually serve http / https traffic above. Then at least some curious can try that.

**Comment by drocsid** [comment] 2020-04-18 21:04
I will draft a deployment section to the http4s docs including instructions for building graal images. Then I also think it will be useful to include this as part of the template to provide as a reference from that documentation. If there are any suggestions or concerns before I start doing that please let me know.

**Comment by rossabaker** [comment] 2020-04-20 03:09
Strong :+1: to the docs piece.

On the g8 piece, what form do you see that taking?  Graal is still a relatively unusual deployment, so I'm hesitant to force that on people.  But if it's just the plugin itself so it's an option, that might be good.  Or we could also maintain a branch, but it's hard enough to keep the g8 templates current as is.

**Comment by jamesward** [comment] 2020-04-23 20:35
Here is an example project that uses http4s with GraalVM via sbt-native-packager:
https://github.com/jamesward/javadoccentral

Notes:
 - The Docker container is based on `scratch` using muslC
 - I don't use logback cause I couldn't get it working
 - I tried just about every http4s client and ended up using okhttp due to issues with all of the others
 - Final container image is 43M and starts up super-duper fast

**Comment by rossabaker** [comment] 2020-04-24 01:08
Thanks, @jamesward. If you remember the issues with the other client backends, we'd be happy to take a look and see which others we can get working.

**Comment by jamesward** [comment] 2020-04-24 14:44
With `blaze-client` it seemed to just hang, but it might have been the GraalVM DNS issues with scatch. With `async-http-client` I had a hard time getting the right GraalVM config due to shaded libs. I tried the `jetty-client` but can't remember what happened.  Thanks for all your support!

**Comment by drocsid** [comment] 2020-04-27 03:02
@rossabaker I have been busy but wrote a draft and example of what I thought a deployment page should look like for http4s that includes two deployment examples. https://github.com/drocsid/http4s/blob/docs/deployment/docs/src/main/tut/deployment.md 

This is what I had envisioned above. I have a few TODOs listed and haven't yet tried anything against your doc tools. Would you like me to continue? After finishing the doc but before PR I would adapt against the gitter8 template as I had suggested above....

**Comment by rossabaker** [comment] 2020-04-27 03:32
This is a good start.  Linking to example projects is probably helpful here.  We have an examples-docker in the repo already.  One thing I don't like is that our examples are scattered across examples modules instead of self-contained, but that problem is probably out of scope for this PR.

Still curious on the g8. Are you thinking it's its own branch, or we integrate the native plugin into the main template?  Does the native image impact the template other than being another plugin, with the prerequisite that GraalVM is installed?

**Comment by drocsid** [comment] 2020-04-27 03:39
@rossabaker all that's required regarding the template might be adding a few resource files, adding the sbt-assembly plugin. Then otherwise we are just showing the native-image command so maybe add a script that contains a command that can be used to build the image. Then I don't see how it really interrupts or interferes with that template.

**Comment by drocsid** [comment] 2020-04-27 03:41
E.G. 

https://github.com/drocsid/https_example/tree/master/src/main/resources/META-INF/native-image/com.example/weatherdemo

https://github.com/drocsid/https_example/blob/master/project/plugins.sbt

https://github.com/drocsid/https_example/blob/master/native-image-build-cmd.sh

**Comment by drocsid** [comment] 2020-04-28 06:34
@rossabaker I made some additions to the documentation and have added to the giter8 template so it has a few additional resources so it may be used to build a native image. I added a property to the template to reference the assembly target path, but could probably remove that and configure the target path via the `sbt-assembly` plugin. I made a mock PR for the template. Could you have a look when you have time?

https://github.com/http4s/http4s.g8/pull/139

https://github.com/drocsid/http4s/blob/docs/deployment/docs/src/main/tut/deployment.md

**Comment by drocsid** [comment] 2020-04-28 06:42
Er mock PR here: https://github.com/drocsid/http4s.g8/pull/1

**Comment by LeifW** [comment] 2020-04-30 07:02
sbt native-packager can be used instead of sbt assembly + invoking `native-image` yourself (as in Jame's example - that's what I've been doing lately when playing around with this stuff myself). Would we want to describe both options in the docs? Or maybe go with this for now, and we can always expand the docs later?

**Comment by jamescosford** [comment] 2020-04-30 07:17
Something else that tripped me up was the inclusion of resources, which won't be included unless you specify them. It's all in the native image docs but my script has grown a bit at this stage:

```
  docker run\
    --memory 12GB\
    --cpus 4\
    --rm -it\
    -v "$FAT_JAR_CP":"/opt/cp"\
    -v "$BUNDLE_DIR":"/opt/graalvm"\
    -v "$CONFIG_DIR":"/opt/cfg"\
    graalvm-native-image\
        -jar /opt/cp/$FAT_JAR_NAME\
        --static\
        --no-server\
        -H:Name=graalni\
        -H:ResourceConfigurationFiles="/opt/cfg/include_resources.json"\
        -H:Log=registerResource:\
        --no-fallback\
        --allow-incomplete-classpath\
        --report-unsupported-elements-at-runtime
```

where `include_resources.json` looks like
```
{
  "resources": [
    {
      "pattern": "reference.conf"
    },
    {
      "pattern": "application.conf"
    }
  ]
}
```

**Comment by drocsid** [comment] 2020-04-30 07:53
> sbt native-packager can be used instead of sbt assembly + invoking `native-image` yourself (as in Jame's example - that's what I've been doing lately when playing around with this stuff myself). Would we want to describe both options in the docs? Or maybe go with this for now, and we can always expand the docs later?

I think we could mention that you could use sbt-native-packager. I don't know what it looks like really but assume it's just a wrapper that triggers the native-image command. Noel chimed in about it above also.

It's my opinion that wrapping the `native-image` command with the `native-packager` places you further away from the `native-image` tooling. I would argue that sometimes it's easier to learn, debug, move more quickly by using a projects tools vs third party wrappers. If you learn the `native-image` command, you can use it beyond SBT. GraalVM is still under heavy development, etc...

> Something else that tripped me up was the inclusion of resources, which won't be included unless you specify them. 

I would agree that including resources in an example might be helpful.

**Comment by drocsid** [comment] 2020-04-30 08:19
Should I open actual PR for above? Any feedback? I spent a few hours writing the deployment page and building and testing the template on https://github.com/http4s/http4s/issues/3299#issuecomment-620409680

**Comment by rossabaker** [comment] 2020-05-01 02:59
@drocsid Nice work!  Yes, please go ahead and open a PR with that.  It'll be easier to comment and make suggestions there than here, but it looks like a wonderful start.

As for the g8 template, I wonder about integrating that with [giter8 conditionals](http://www.foundweekends.org/giter8/template.html#Conditionals).  Just have a graalvm boolean in the initial questions, and it'll add the config for people who ask for it.  Then there's only one branch of the g8 to maintain per http4s version.  In the meantime, I wouldn't mind just having a separate branch.

**Comment by drocsid** [comment] 2020-05-04 02:13
@rossabaker here's the PRs. I made the suggested changes using conditionals for the g8 template.

https://github.com/http4s/http4s.g8/pull/143

https://github.com/http4s/http4s/pull/3374

**Comment by LeifW** [comment] 2020-05-04 06:26
@drocsid I adopted @noelwelsh's example and switched it to use sbt native packager: https://github.com/LeifW/http4s-native-image/blob/sbt_native_packager/build.sbt#L39
 I'm not normally wild about having a Java DSL generate a bunch of shell scripts (a la a lot of the other stuff that SBT native packager does), but for its invocation of native-image it's just the difference between running `sbt assembly && native-image -jar path/to/assembly/jar --other --args` and running `sbt graalvm-native-image:packageBin`, with the other args in that `Seq[String]` in the `graalVMNativeImageOptions` sbt setting. The mapping is pretty direct. So it's either using the assembly, or native packager plugin. I think an advantage of using the native packager variant is not having to keepthe path of the build artifact (the jar) in sync between the steps - I also take advantage of that when passing the build artifact from the native-image step, `(packageBin in GraalVMNativeImage).value` to the docker (from sbt docker) step below in the build.sbt file. The compile, assembly, and native-image steps do take some time, so it's nice to have one command to run them all together.
And I know sometimes it can be annoying to resolve conflicting files between the jars to get everything to fit in an assembly jar (though maybe that's for the best - to avoid potential ambiguities with classloader order).
Personally, I think I prefer using sbt native packager for this for personal development, but I think people will have different requirements and prefer whichever option fits in best with their existing workflow. I think we could easily document both, as the difference between them is minimal (unless that would be confusing).

**Comment by drocsid** [comment] 2020-05-05 02:46
@LeifW it's really not terribly different as you mention. My preference is being closer to the native-image command when getting started, because it's easier to talk to graal devs with the command than an sbt wrapper example. 

When looking for native-image command parameters, the proper place to look is the graal docs. If something goes wrong you're probably better off dropping to the command to ensure the wrapper hasn't caused a problem.

Do you want to add the equivalent SBT command somewhere, maybe additionally add docker? Maybe we could point to it from the documentation?

**Comment by drocsid** [comment] 2020-05-05 02:49
@rossabaker Looks like I failed the documentation step on https://github.com/http4s/http4s/pull/3374 . Do you have advice on following up?

**Comment by armanbilge** [comment] 2022-05-01 22:51
https://github.com/http4s/http4s/pull/3374 is merged and I think the g8 covers this too.

**Closed by armanbilge** 2022-05-01 22:51 UTC
Labels: docs
