### ISSUE TITLE
[feature] Expose connection pool manager's waitQueue size

### ISSUE THREAD

**Issue by anilkumarmyla** [http4s/http4s#2883] opened 2019-09-23 22:16 UTC
Our use-case is to log this metric to drive decrease/increase in compute instances

https://github.com/http4s/http4s/blob/master/client/src/main/scala/org/http4s/client/PoolManager.scala#L47

**Comment by kevinmeredith** [comment] 2019-10-16 02:59
My initial thought was adding a `def waitQueueSize: F[Int]` to [trait ConnectionManager](https://github.com/http4s/http4s/blob/series/0.20/client/src/main/scala/org/http4s/client/ConnectionManager.scala#L18).

But, per https://stackoverflow.com/a/18369508/409976, I'm not sure if it would break binary compatibility.

Thoughts, please, @rossabaker and @ChristopherDavenport?

**Comment by kevinmeredith** [comment] 2019-10-20 04:30
Any thoughts, please, Chris or Ross?

**Comment by rossabaker** [comment] 2021-04-11 04:11
Basically a duplicate of #1270

**Closed by rossabaker** 2021-04-11 04:11 UTC
