### ISSUE TITLE
Websocket fails with a Kleisli Routes monad

### ISSUE THREAD

**Issue by pjan** [http4s/http4s#3697] opened 2020-09-18 15:18 UTC
Minimal example:

```scala
import scala.concurrent.duration._

import cats.implicits._
import cats.data.Kleisli
import cats.effect._
import fs2._
import org.http4s._
import org.http4s.dsl.Http4sDsl
import org.http4s.implicits._
import org.http4s.server.blaze._
import org.http4s.server.websocket.WebSocketBuilder
import org.http4s.websocket.WebSocketFrame

case class WebSocketRoutes[F[_]: Concurrent: Timer]() extends Http4sDsl[F] {

  val routes: HttpRoutes[F] = HttpRoutes.of[F] {
    case GET -> Root =>
      val toClient: Stream[F, WebSocketFrame] =
        Stream.awakeEvery[F](1.seconds).map(d => WebSocketFrame.Text(s"Ping! $d"))
      val fromClient: Pipe[F, WebSocketFrame, Unit] = _.evalMap {
        case WebSocketFrame.Text(t, _) => F.delay(println(t))
        case f                         => F.delay(println(s"Unknown type: $f"))
      }
      WebSocketBuilder[F].build(toClient, fromClient)
  }

}

object Middleware {

  def apply[F[_]: Sync](
      name: String
  )(httpApp: HttpApp[Kleisli[F, String, *]]): HttpApp[F] =
    Kleisli { request =>
      for {
        appRequest <- F.pure(request.mapK(Kleisli.liftK[F, String]))
        appResponse <- httpApp.run(appRequest).run(name)
        response = appResponse.mapK(Kleisli.applyK(name))
      } yield response
    }

}

object Main extends IOApp {

  type AppIO[A] = Kleisli[IO, String, A]

  def run(args: List[String]): IO[ExitCode] = {
    val routes = WebSocketRoutes[AppIO]().routes.orNotFound

    val app = Middleware("test")(routes)

    BlazeServerBuilder[IO](scala.concurrent.ExecutionContext.global)
      .bindHttp(8080, "localhost")
      .withHttpApp(app)
      .serve
      .compile
      .drain
      .as(ExitCode.Success)

  }

}
```

Full Stack trace:
```
[info] 23:11:17.950 [blaze-selector-1] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:51343
[info] 23:11:17.974 [ioapp-compute-1] DEBUG org.http4s.server.blaze.Http1ServerStage$$anon$1 - Websocket key: Some(WebSocketContext(WebSocket(Stream(..),org.http4s.server.websocket.WebSocketBuilder$Builder$$Lambda$299/1538312351@2487cace,Kleisli(cats.data.KleisliFunctions$$Lambda$298/754950929@33f502e0)),Headers(),Kleisli(cats.data.KleisliFunctions$$Lambda$298/754950929@365d5f01)))
[info] Request headers: Headers(Host: 127.0.0.1:8080, Connection: Upgrade, Upgrade: websocket, Sec-WebSocket-Version: 13, Sec-WebSocket-Key: 4+mLlx5cT/kKSia8zG5MSw==)
[info] 23:11:17.985 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.Http1ServerStage$$anon$1 - Switching pipeline segments for websocket
[info] 23:11:17.999 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.Http1ServerStage$$anon$1 - Shutting down HttpPipeline
[info] 23:11:18.000 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.Http1ServerStage$$anon$1 - Canceled request
[info] 23:11:18.000 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.Http1ServerStage$$anon$1 - Shutting down.
[info] 23:11:18.000 [scala-execution-context-global-38] DEBUG org.http4s.blazecore.IdleTimeoutStage - Stage IdleTimeoutStage sending inbound command: Connected
[info] 23:11:18.000 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.WebSocketDecoder - Starting up.
[info] 23:11:18.000 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.WebSocketDecoder - Stage WebSocketDecoder sending inbound command: Connected
[info] 23:11:18.000 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.WSFrameAggregator - Starting up.
[info] 23:11:18.000 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.WSFrameAggregator - Stage WSFrameAggregator sending inbound command: Connected
[info] 23:11:18.000 [scala-execution-context-global-38] DEBUG org.http4s.blazecore.websocket.Http4sWSStage - Starting up.
[info] 23:11:18.006 [scala-execution-context-global-38] ERROR org.http4s.server.blaze.WSFrameAggregator - Exception caught when attempting inbound command
[info] java.lang.ClassCastException: cats.data.Kleisli cannot be cast to cats.effect.IO
[info]  at cats.effect.IOLowPriorityInstances$IOEffect.attempt(IO.scala:863)
[info]  at cats.syntax.ApplicativeErrorOps$.attempt$extension(applicativeError.scala:52)
[info]  at org.http4s.blazecore.websocket.Http4sWSStage.stageStartup(Http4sWSStage.scala:132)
[info]  at org.http4s.blaze.pipeline.Stage.inboundCommand(Stages.scala:75)
[info]  at org.http4s.blaze.pipeline.Stage.inboundCommand$(Stages.scala:73)
[info]  at org.http4s.blazecore.websocket.Http4sWSStage.inboundCommand(Http4sWSStage.scala:26)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand(Stages.scala:258)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand$(Stages.scala:254)
[info]  at org.http4s.server.blaze.WSFrameAggregator.sendInboundCommand(WSFrameAggregator.scala:22)
[info]  at org.http4s.blaze.pipeline.Head.inboundCommand(Stages.scala:276)
[info]  at org.http4s.blaze.pipeline.Head.inboundCommand$(Stages.scala:274)
[info]  at org.http4s.server.blaze.WSFrameAggregator.inboundCommand(WSFrameAggregator.scala:22)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand(Stages.scala:258)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand$(Stages.scala:254)
[info]  at org.http4s.server.blaze.WebSocketDecoder.sendInboundCommand(WebSocketDecoder.scala:14)
[info]  at org.http4s.blaze.pipeline.Head.inboundCommand(Stages.scala:276)
[info]  at org.http4s.blaze.pipeline.Head.inboundCommand$(Stages.scala:274)
[info]  at org.http4s.server.blaze.WebSocketDecoder.inboundCommand(WebSocketDecoder.scala:14)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand(Stages.scala:258)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand$(Stages.scala:254)
[info]  at org.http4s.blazecore.IdleTimeoutStage.sendInboundCommand(IdleTimeoutStage.scala:18)
[info]  at org.http4s.blaze.pipeline.Tail.replaceTail(Stages.scala:183)
[info]  at org.http4s.blaze.pipeline.Tail.replaceTail$(Stages.scala:162)
[info]  at org.http4s.server.blaze.Http1ServerStage.replaceTail(Http1ServerStage.scala:73)
[info]  at org.http4s.server.blaze.WebSocketSupport.$anonfun$renderResponse$7(WebSocketSupport.scala:83)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
[info]  at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[info]  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info]  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info]  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info]  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info] 23:11:18.006 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.WSFrameAggregator - Shutting down.
[info] 23:11:18.006 [scala-execution-context-global-38] DEBUG org.http4s.server.blaze.WebSocketDecoder - Shutting down.
[info] 23:11:18.006 [scala-execution-context-global-38] DEBUG org.http4s.blazecore.IdleTimeoutStage - Shutting down idle timeout stage
[info] 23:11:18.006 [scala-execution-context-global-38] DEBUG org.http4s.blazecore.IdleTimeoutStage - Shutting down.
[info] 23:11:18.006 [scala-execution-context-global-38] DEBUG org.http4s.blaze.channel.nio1.NIO1HeadStage - Shutting down.
[info] 23:11:18.007 [blaze-selector-1] ERROR org.http4s.blaze.channel.nio1.NIO1HeadStage - Abnormal NIO1HeadStage termination
[info] java.lang.ClassCastException: cats.data.Kleisli cannot be cast to cats.effect.IO
[info]  at cats.effect.IOLowPriorityInstances$IOEffect.attempt(IO.scala:863)
[info]  at cats.syntax.ApplicativeErrorOps$.attempt$extension(applicativeError.scala:52)
[info]  at org.http4s.blazecore.websocket.Http4sWSStage.stageStartup(Http4sWSStage.scala:132)
[info]  at org.http4s.blaze.pipeline.Stage.inboundCommand(Stages.scala:75)
[info]  at org.http4s.blaze.pipeline.Stage.inboundCommand$(Stages.scala:73)
[info]  at org.http4s.blazecore.websocket.Http4sWSStage.inboundCommand(Http4sWSStage.scala:26)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand(Stages.scala:258)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand$(Stages.scala:254)
[info]  at org.http4s.server.blaze.WSFrameAggregator.sendInboundCommand(WSFrameAggregator.scala:22)
[info]  at org.http4s.blaze.pipeline.Head.inboundCommand(Stages.scala:276)
[info]  at org.http4s.blaze.pipeline.Head.inboundCommand$(Stages.scala:274)
[info]  at org.http4s.server.blaze.WSFrameAggregator.inboundCommand(WSFrameAggregator.scala:22)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand(Stages.scala:258)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand$(Stages.scala:254)
[info]  at org.http4s.server.blaze.WebSocketDecoder.sendInboundCommand(WebSocketDecoder.scala:14)
[info]  at org.http4s.blaze.pipeline.Head.inboundCommand(Stages.scala:276)
[info]  at org.http4s.blaze.pipeline.Head.inboundCommand$(Stages.scala:274)
[info]  at org.http4s.server.blaze.WebSocketDecoder.inboundCommand(WebSocketDecoder.scala:14)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand(Stages.scala:258)
[info]  at org.http4s.blaze.pipeline.Head.sendInboundCommand$(Stages.scala:254)
[info]  at org.http4s.blazecore.IdleTimeoutStage.sendInboundCommand(IdleTimeoutStage.scala:18)
[info]  at org.http4s.blaze.pipeline.Tail.replaceTail(Stages.scala:183)
[info]  at org.http4s.blaze.pipeline.Tail.replaceTail$(Stages.scala:162)
[info]  at org.http4s.server.blaze.Http1ServerStage.replaceTail(Http1ServerStage.scala:73)
[info]  at org.http4s.server.blaze.WebSocketSupport.$anonfun$renderResponse$7(WebSocketSupport.scala:83)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
[info]  at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[info]  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info]  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info]  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info]  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info] 23:11:18.007 [blaze-selector-1] DEBUG org.http4s.blaze.channel.nio1.NIO1HeadStage - Stage NIO1HeadStage sending inbound command: Disconnected
[info] 23:11:18.007 [blaze-selector-1] DEBUG org.http4s.blazecore.IdleTimeoutStage - Shutting down idle timeout stage
[info] 23:11:18.007 [blaze-selector-1] DEBUG org.http4s.blazecore.IdleTimeoutStage - Shutting down.
[info] 23:11:18.007 [blaze-selector-1] DEBUG org.http4s.blazecore.IdleTimeoutStage - Stage IdleTimeoutStage sending inbound command: Disconnected
[info] 23:11:18.007 [blaze-selector-1] DEBUG org.http4s.server.blaze.WebSocketDecoder - Shutting down.
[info] 23:11:18.007 [blaze-selector-1] DEBUG org.http4s.server.blaze.WebSocketDecoder - Stage WebSocketDecoder sending inbound command: Disconnected
[info] 23:11:18.007 [blaze-selector-1] DEBUG org.http4s.server.blaze.WSFrameAggregator - Shutting down.
[info] 23:11:18.008 [blaze-selector-1] DEBUG org.http4s.server.blaze.WSFrameAggregator - Stage WSFrameAggregator sending inbound command: Disconnected
[info] 23:11:18.010 [blaze-selector-1] DEBUG org.http4s.blazecore.websocket.Http4sWSStage - Shutting down.
```

I tried debugging it for a the past 2 hours, but I'm not deep enough in the http4s codebase to resolve this within a reasonable amount of time. Hopeful the solution for this will be obvious to someone around here.

**Comment by yoohaemin** [comment] 2020-09-19 04:32
Looks like the problem's with the `attribute` field of the response.

When you do this:
```scala
        response = appResponse.mapK(Kleisli.applyK(name))
```
`mapK` doesn't run every `Kleisli` and turn it back into `F` (despite the type telling you so!)

See the implementation of `mapK`:

https://github.com/http4s/http4s/blob/fef26ec6c14433490969a8e5bd221121288c8de0/core/src/main/scala/org/http4s/Message.scala#L529-L536

The `attributes`  field is passed as-is without any modification.

See how the `WebSocket` object is stored inside `Response`.

https://github.com/http4s/http4s/blob/b6608e43682b37529a299ce5ab05994e102c2bd0/server/src/main/scala/org/http4s/server/websocket/WebSocketBuilder.scala#L75-L77

All of its fields, the `send`/`receive` streams and `onClose` effect are still `Kleisli`s even after `mapK` -- so if you try to run them with `IO`, it blows up with a `ClassCastException`.

**Comment by pjan** [comment] 2020-09-19 08:51
Thanks for the pointer, @yoohaemin.

Based on this, I dug a bit deeper and was able to resolve this in a local branch, but the changes required, while straightforward, break the current API:

- pull the `WebSocketContext` out of the `attributes` in its own variable on the `Response`

```scala
final case class Response[F[_]](
    status: Status = Status.Ok,
    httpVersion: HttpVersion = HttpVersion.`HTTP/1.1`,
    headers: Headers = Headers.empty,
    body: EntityBody[F] = EmptyBody,
    attributes: Vault = Vault.empty,
    wsCtx: Option[WebSocketContext[F]] = None
) extends Message[F] ...
```

- `mapK` on response needs to act on the `wsCtx`. Given that `WebSocketContext[F]` wraps around `WebSocket`, and `WebSocket[F]` has a `Pipe[F]`, we also need the inverse natural translation of `F ~> G` (G ~> F), so the shape is more that of what is called `translate` within this codebase. We need a functor instance of F, since `WebsocketContext[F]` has `failureResponse` as `F[Response[F]]` which we need to become `G[Response[G]]`

(for `Response[F]`: `mapK` -> `translate`)
```scala
  def translate[G[_]](fk: F ~> G)(gK: G ~> F)(implicit F: Functor[F]): Response[G] =
    Response[G](
      status = status,
      httpVersion = httpVersion,
      headers = headers,
      body = body.translate(fk),
      attributes = attributes,
      wsCtx = wsCtx.map(_.translate(fk)(gK))
    )
```

(for `WebsocketContext`: `translate`)
```scala
  def translate[G[_]](fk: F ~> G)(gK: G ~> F)(implicit F: Functor[F]): WebSocketContext[G] =
    WebSocketContext[G](
      webSocket.translate(fk)(gK),
      headers,
      fk(F.map(failureResponse)(_.translate(fk)(gK)))
    )
```

(for `Websocket`: `translate`)
```scala
  def translate[G[_]](fk: F ~> G)(gK: G ~> F): WebSocket[G] =
    WebSocket[G](
      send = send.translate(fk),
      receive = stream => receive(stream.translate(gK)).translate(fk),
      onClose = fk(onClose)
    )
```

- Update `build` of `WebsocketBuilder` to store the context in the newly introduced `wsCtx` variable on the `Response` instead of in the `arguments`

```scala
def build(
  ...
): F[Response[F] = {
  ...

       WebSocketBuilder(
        send,
        finalReceive,
        headers,
        onNonWebSocketRequest,
        onHandshakeFailure).onNonWebSocketRequest
        .map(
          _.copy(wsCtx = Some(
            WebSocketContext(WebSocket(send, finalReceive, onClose), headers, onHandshakeFailure)))
...
}
```

- some minor changes (pattern match of `Response`, calling of `mapK` on response, ...) in `Logger.scala`, `Client.scala`, `Status.scala`, `Message.scala` and `KleisliSyntax.scala`

Stats:  9 files changed, 43 insertions(+), 20 deletions(-)

LMK if this is an acceptable solution, @rossabaker. If so, I'm happy to open a PR, even addressing suggestions one might have on how to do it more elegantly.

**Comment by yoohaemin** [comment] 2020-09-19 11:13
@pjan I think this could definitely work and a cleaner solution of the root cause. However, if the maintainers decide that the api breakage is a problem I can think of another way to solve this. 

We could store a list of `FunctionK`s in the vault, and append at the list whenever `mapK` in the `Response` is called. After that, when the websocket stuffs are actually invoked, run `foldK` on that list and apply the resulting `FunctionK` to the websocket effects. This ensures no `FunctionK`s are thrown away, and there will be no api breakage. 

If performance of storing a list is a problem, we could take the eager route and store a single `FunctionK`, but compose them with a new one whenever `mapK` is called.

WDYT?

**Comment by pjan** [comment] 2020-09-20 05:04
Given that we need both an `F ~> G` as well as a `G ~>F` for the transformation of the `Pipe` (inside the Websocket > WebsocketContext > Response) for this to work, it would still come with API breakage.

**Comment by hamnis** [comment] 2020-09-21 06:20
Good find @pjan 

Not all backends support Websockets at the moment, leaving us with a problem of how to model this without having to expose it in the base model. Attributes swallows the original type, but exposing it as a response field may signal to users that all backends support websockets. IDK what is the best solution here. We cannot query the attributes of which effectful attributes exists. Meaning that if we continue storing them there, we would need to mapK them as well, and maybe allow users to translate user-defined attribute keys as well. 

Api breakages needs to to target the master branch.

**Comment by Rosteelton** [comment] 2020-11-03 15:22
@pjan Have you resolved this problem in your project somehow? or just forked http4s

**Comment by rossabaker** [comment] 2020-11-08 19:57
Yeah, it seems like we're definitely in breaking change territory here.  Great work finding the cause of the problem.

The current model of trying to smuggle a web socket through a `Response` is impossible to support on the servlet backends, even though servlets support web sockets.  Elevating it to a field on the response as proposed here would solve this issue, but not permit broader backend support.  If we're making a breaking change, I wonder about separating web sockets from `HttpApp` / `HttpRoutes` entirely: two different Kleisli shapes, each with their own mount method on the backend builders.  This would unfortunately push some additional routing logic into Blaze and probably Ember.

Another thing that makes me hesitant to elevate the websocket to a field on the response is that it will cost memory on the vast majority of responses in the http4s universe that aren't web sockets.

**Comment by rossabaker** [comment] 2021-04-11 20:55
On the servlet front, not that people are clamoring for that support, the current model will be possible in Jetty 10.  So that argument against the status quo is weakened.

Would still like to find a way around this.

**Comment by rossabaker** [comment] 2021-04-18 04:17
Opening it up would get around the memory concerns, but we almost always end up regretting subtyping.  There's so much to think about on all the return types.  I'd consider reviving the idea of `Message` as a typeclass before subtyping.

**Comment by vasilmkd** [comment] 2021-04-18 08:38
As a temporary band aid, could `Request` be `sealed` too?

**Comment by rossabaker** [comment] 2021-04-26 05:21
We have `ContextRequest` and `ContextResponse` for the "more compositional" approach, but I think this demands subtyping: it still has to be a request coming in and a response going out.

I guess sealing it would work, but everything else websocket is neatly tucked away into its package.  That feels like an awful hack.

**Comment by vasilmkd** [comment] 2021-04-26 20:29
I'm working on this.

**Comment by vasilmkd** [comment] 2021-04-26 21:46
@pjan is absolutely correct. To translate a `WebSocket[F]` to a `WebSocket[G]`, both an `F ~> G` and `G ~> F` and `Functor[F]` are needed. If we look at the existing API (`mapK` exists on `Response[F]`, but not `translate`), IMO, it is a violation to stick a `WebSocket[F]` inside a `Response[F]`, because we are essentially lying that it is possible to then `mapK` the resulting `Response[F]` which contains the websocket. So even if we do solve the problem of providing the `f: F ~> G` to the websocket object, it is still not enough to achieve a proper translation.

**Comment by vasilmkd** [comment] 2021-04-26 22:55
So, maybe a subtype of `Response` with a `def translate[G[_]](f: F ~> G, g: G ~> F): WSResponse[G]` is the only lawful way to proceed...

**Comment by armanbilge** [comment] 2022-05-02 00:02
Fixed in https://github.com/http4s/http4s/pull/5152 I believe.

**Closed by armanbilge** 2022-05-02 00:02 UTC
Labels: bug, RFC, module:server
