### ISSUE TITLE
[ember-client] IOException: Connection reset by peer

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#3717] opened 2020-09-29 16:29 UTC
Recently I was testing different backends in my prod application.
When I changed the existing code (working fine with blaze) to use ember, I notice many instances of this exception:

The exception is caught correctly and returned from my `client.run` call, ultimately, but it's surprising that this happens so much (thousands of instances).

- java 8
- Scala 2.12.12
- fs2 2.4.4
- http4s 0.21.7

```
java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(FileDispatcherImpl.java)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:197)
    at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:388)
    at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
    at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
    at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
    at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    at async @ fs2.io.package$.asyncYield(io.scala:233)
    at flatMap @ fs2.io.tcp.SocketGroup.$anonfun$apply$8(SocketGroup.scala:274)
    at flatMap @ fs2.io.tcp.SocketGroup.getBufferOf$1(SocketGroup.scala:243)
    at flatMap @ fs2.io.tcp.SocketGroup.fs2$io$tcp$SocketGroup$$read0$1(SocketGroup.scala:273)
```

**Comment by rossabaker** [comment] 2020-10-12 04:30
What kind of requests?  GETs, POSTs, both?

**Comment by agourlay** [comment] 2020-10-16 11:42
I am seeing this as well with `0.21.8` for GETs and POSTs for what I can see.

**Comment by rossabaker** [comment] 2021-04-11 21:00
Anybody have an easy reproduction?

**Comment by tpataky** [comment] 2021-04-28 14:35
Hi @rossabaker ! Not sure if this is the exact same problem as @Daenyth's, but I do have a minimalistic example that produces a very similar result.

```scala
package fml.calcsvc

import cats.effect.{ExitCode, IO, IOApp}
import cats.implicits._
import org.http4s.dsl.io._
import org.http4s.syntax.kleisli._
import org.http4s.HttpRoutes
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.ember.server.EmberServerBuilder

object Bug extends IOApp {

  val app = HttpRoutes.of[IO] {
    case GET -> Root => Ok()
  }

  override def run(args: List[String]): IO[ExitCode] = {
    (EmberServerBuilder.default[IO].withHttpApp(app.orNotFound).build,
      EmberClientBuilder.default[IO].build).tupled.use {
      case (server, client) =>
        for {
          _ <- IO(println("1"))
          _ <- client.get(server.baseUri)(_.body.compile.drain)
          _ <- IO(println("2"))
          _ <- client.get(server.baseUri)(_.body.compile.drain)
          _ <- IO(println("3"))
          _ <- client.get(server.baseUri)(_.body.compile.drain)
          _ <- IO(println("4"))
          _ <- client.get(server.baseUri)(_.body.compile.drain)
          _ <- IO(println("5"))
          _ <- client.get(server.baseUri)(_.body.compile.drain)
        } yield ExitCode.Success
    }
  }
}

```

When run it prints the following:
```
1
2
3
java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl.write0(Native Method)
	at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl$WriteTask.run(WindowsAsynchronousSocketChannelImpl.java:776)
	at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl.implWrite(WindowsAsynchronousSocketChannelImpl.java:912)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:383)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:400)
	at fs2.io.tcp.SocketGroup.$anonfun$apply$18(SocketGroup.scala:322)
	at fs2.io.tcp.SocketGroup.$anonfun$apply$18$adapted(SocketGroup.scala:315)
	at async @ fs2.io.package$.asyncYield(io.scala:245)
	at guarantee @ fs2.io.package$.asyncYield(io.scala:245)
	at flatMap @ fs2.io.tcp.SocketGroup.go$3(SocketGroup.scala:334)
	at apply @ fs2.Stream$.$anonfun$parJoin$1(Stream.scala:2065)
	at acquire @ fs2.Stream$.$anonfun$parJoin$14(Stream.scala:2107)
	at apply @ fs2.Stream$.$anonfun$parJoin$1(Stream.scala:2065)
	at withPermit @ fs2.io.tcp.SocketGroup.fs2$io$tcp$SocketGroup$$read0$1(SocketGroup.scala:290)
	at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:413)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
```

Library versions:
val catsVersion       = "2.2.0"
val catsEffectVersion = "2.2.0"
val fs2Version        = "2.4.5"
val http4sVersion     = "0.21.13"

**Comment by hamnis** [comment] 2021-04-28 14:51
@tpataky  is this still reproducable with the latest version? There have been quite a few ember fixes lately. Try with 0.21.22

**Comment by tpataky** [comment] 2021-04-28 19:32
Will try it later, but I'm thinking this could be related to (or the same as https://github.com/http4s/http4s/issues/4731).

**Comment by RaasAhsan** [comment] 2021-05-05 08:14
I think this one is different from #4731 , which has been solved now. The issue there was that the server was writing back a request stream to the response stream, but it was completing the request before the body was fully written.

**Comment by tpataky** [comment] 2021-05-06 19:38
Looks like the problem has been fixed in 0.21.22! I can no longer reproduce it with that version. Thanks everyone!

**Comment by rossabaker** [comment] 2021-05-06 20:05
A couple reporters, but sounds fixed.  We'll reopen if anyone sees this on a current version.  Thanks for retesting!

**Closed by rossabaker** 2021-05-06 20:05 UTC
Labels: bug, module:ember-client

**Comment by RaasAhsan** [comment] 2021-05-09 23:36
@Daenyth if you ever get the time and willingness, could you could repeat your experiment with the latest 0.21 release? It sounds like we may have fixed this in the past few releases, but we're still aware of an edge case where this will manifest. I'm wondering if that's what you're seeing
