### ISSUE TITLE
"CORS headers were denied" excessive log messages

### ISSUE THREAD

**Issue by mxl** [http4s/http4s#931] opened 2017-02-19 06:30 UTC
CORS middleware [writes](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/CORS.scala#L107) info log message even if there is no CORS headers in request.

**Comment by mxl** [comment] 2017-02-19 07:49
See example in https://github.com/http4s/http4s/issues/932

**Comment by rossabaker** [comment] 2017-02-19 19:21
Is the problem just that it logs multiple times (I agree, that's unfortunate), or also that it's `info` instead of `debug`?

**Comment by rossabaker** [comment] 2017-02-19 19:32
Did you notice this logging twice in 0.14.x?  I have a bad feeling that #933 is a result of a change to `Fallthrough`, and if this behavior changed too, that furthers my theory.

**Comment by rossabaker** [comment] 2017-02-19 19:37
Can answer this myself thanks to your test example: the duplicate logging is not new.

**Comment by rossabaker** [comment] 2017-02-19 20:00
If you use a Router, like in [this example](https://github.com/rossabaker/http4s-support/commit/3934268eb76ea05ab0c66b677386023a801cce66), it won't log twice.  Pulling out that prefix may be a better or worse solution, depending on the architecture of your app.

The problem is that multiple mounts assemble a single `HttpService` via `orElse` composition.  When the first service wrapped in `cors` logs and falls through, the second service is consulted, which also logs and falls through.  I think eliminating this duplicate logging could be challenging, though reasonable workarounds exist.

**Comment by mxl** [comment] 2017-02-19 20:10
This issue is not about duplicate logging. Maybe I used the word "excessive" in the wrong way (I'm not native English speaker) and word "redundant" is more appropriate here. This issue is only about that "CORS headers were denied" is logged even if there were no CORS headers in request.

**Comment by mxl** [comment] 2017-02-19 20:29
I'm not sure that logging this message in case where there were no CORS headers is wrong. Maybe I'm missing something in understanding how CORS works but when http service is called not by browser but by mobile application where CORS mechanism is not used this message seems unnecessary.

**Comment by ChristopherDavenport** [comment] 2017-02-20 13:53
Closed by #935  We will be looking to put out a patch version shortly.

**Closed by ChristopherDavenport** 2017-02-20 13:53 UTC
