### ISSUE TITLE
[ember] error parsing responses with ember client

### ISSUE THREAD

**Issue by tpolecat** [http4s/http4s#3732] opened 2020-10-09 19:59 UTC
I sporadically get this error from Ember client when making a request. I'm on version 0.21.7+45-4eb03e47-SNAPSHOT

```
org.http4s.ember.core.Parser$Response$RespPrelude$RespPreludeError: Received Error while parsing prelude - Reached Ended of Stream Looking for Response Prelude
	at org.http4s.ember.core.Parser$Response$RespPrelude$.$anonfun$parsePrelude$6(Parser.scala:422)
	at org.http4s.ember.core.Parser$Response$RespPrelude$.$anonfun$parsePrelude$6$adapted(Parser.scala:401)
	at fs2.Pull$.$anonfun$flatMap$1(Pull.scala:64)
	at fs2.internal.FreeC$$anon$1.cont(Algebra.scala:33)
	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.<init>(Algebra.scala:222)
	at fs2.internal.FreeC$ViewL$$anon$9.cont(Algebra.scala:222)
	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.cont(Algebra.scala:224)
	at fs2.internal.FreeC$ViewL$.mk(Algebra.scala:213)
	at fs2.internal.FreeC$ViewL$.apply(Algebra.scala:202)
	at fs2.internal.FreeC.viewL(Algebra.scala:86)
	at fs2.internal.FreeC$.go$1(Algebra.scala:399)
	at fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:438)
	at fs2.internal.FreeC$.$anonfun$compile$1(Algebra.scala:415)
	at make @ natchez.jaeger.Jaeger$.entryPoint(Jaeger.scala:29)
	at make @ natchez.jaeger.Jaeger$.entryPoint(Jaeger.scala:29)
Caused by: java.lang.Throwable: Reached Ended of Stream Looking for Response Prelude
	at org.http4s.ember.core.Parser$Response$RespPrelude$.$anonfun$parsePrelude$6(Parser.scala:422)
	at org.http4s.ember.core.Parser$Response$RespPrelude$.$anonfun$parsePrelude$6$adapted(Parser.scala:401)
	at fs2.Pull$.$anonfun$flatMap$1(Pull.scala:64)
	at fs2.internal.FreeC$$anon$1.cont(Algebra.scala:33)
	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.<init>(Algebra.scala:222)
	at fs2.internal.FreeC$ViewL$$anon$9.cont(Algebra.scala:222)
	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.cont(Algebra.scala:224)
	at fs2.internal.FreeC$ViewL$.mk(Algebra.scala:213)
	at fs2.internal.FreeC$ViewL$.apply(Algebra.scala:202)
	at fs2.internal.FreeC.viewL(Algebra.scala:86)
	at fs2.internal.FreeC$.go$1(Algebra.scala:399)
	at fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:438)
	at fs2.internal.FreeC$.$anonfun$compile$1(Algebra.scala:415)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:181)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:455)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:466)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:474)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:177)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:455)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:476)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by agourlay** [comment] 2020-10-16 11:45
I am seeing this as well on `0.21.8`

Sharing stacktrace with slightly different line numbers.
```
org.http4s.ember.core.Parser$Response$RespPrelude$RespPreludeError: Received Error while parsing prelude - Reached Ended of Stream Looking for Response Prelude
  	at org.http4s.ember.core.Parser$Response$RespPrelude$.$anonfun$parsePrelude$6(Parser.scala:420)
  	at org.http4s.ember.core.Parser$Response$RespPrelude$.$anonfun$parsePrelude$6$adapted(Parser.scala:399)
  	at fs2.Pull$.$anonfun$flatMap$1(Pull.scala:64)
  	at fs2.internal.FreeC$$anon$1.cont(Algebra.scala:33)
  	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.<init>(Algebra.scala:222)
  	at fs2.internal.FreeC$ViewL$$anon$9.cont(Algebra.scala:222)
  	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.cont(Algebra.scala:224)
  	at fs2.internal.FreeC$ViewL$.mk(Algebra.scala:213)
  	at fs2.internal.FreeC$ViewL$.apply(Algebra.scala:202)
  	at fs2.internal.FreeC.viewL(Algebra.scala:86)
  	at fs2.internal.FreeC$.go$1(Algebra.scala:399)
  	at fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:438)
```

**Comment by kubukoz** [comment] 2021-02-23 00:12
0.21.18 here...

```scala

[E] org.http4s.ember.core.Parser$Response$RespPrelude$RespPreludeError: Received Error while parsing prelude - Message: Cannot Parse Empty Stream - None
[E] 	at org.http4s.ember.core.Parser$Response$RespPrelude$.<clinit>(Parser.scala:424)
[E] 	at org.http4s.ember.core.Parser$Response$.$anonfun$parser$5(Parser.scala:394)
[E] 	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:261)
[E] 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$17(Algebra.scala:545)
[E] 	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
[E] 	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
[E] 	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
[E] 	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)
[E] 	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
[E] 	at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:242)
[E] 	at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:241)
[E] 	at flatMap @ fs2.internal.FreeC$.closeAndGo$1(Algebra.scala:544)
[E] 	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:568)
[E] 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
[E] 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
[E] 	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:261)
[E] 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$17(Algebra.scala:545)
[E] 	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
```

**Comment by rossabaker** [comment] 2021-04-11 21:05
Duplicate of #3667.

**Closed by rossabaker** 2021-04-11 21:05 UTC
Labels: bug
