### ISSUE TITLE
Consider moving from Seq to List in value types

### ISSUE THREAD

**Issue by bpholt** [http4s/http4s#2096] opened 2018-09-17 16:29 UTC
As discussed in #2086, the new monoid instance for `UrlForm` has to duplicate some code from cats-kernel because there is no upstream `Monoid[Seq[?]]` instance. 

It would be a breaking change, but should the definition of `UrlForm` be changed (maybe along with any other type using `Seq`)?

**Comment by jmcardon** [comment] 2018-09-17 17:40
Related: https://github.com/http4s/http4s/issues/1695

**Comment by rossabaker** [comment] 2018-09-17 20:17
`List`, `Vector`, and `Chain` are the three obvious choices.  `Chain` is great if you're combining them often, but I'm not sure how common it is, even if it motivated the other ticket.  It's not random access, so I'm not too keen on `Vector`.  Maybe `List`, and be smart about how we build them?

**Comment by ChristopherDavenport** [comment] 2018-09-17 20:36
What is the downside to `Chain`?

**Comment by rossabaker** [comment] 2018-09-17 20:50
I don't have a firm grasp on its constant factors, and these are generally going to be small enough that Big O isn't critical.  It definitely could be combined effectively without any special `ListBuffer` foofery that would be tempting for a `combineAll` override.

**Comment by rossabaker** [comment] 2018-11-15 00:11
Partially done by #2262.  Demilestoning, because we shouldn't hold up the rest of the release on it.

**Comment by calvinbrown085** [comment] 2018-11-28 13:15
Just looking for other work here, would this be a candidate? https://github.com/http4s/http4s/blob/master/dsl/src/main/scala/org/http4s/dsl/impl/Path.scala#L47

**Comment by rossabaker** [comment] 2020-06-29 19:27
Expounded on a better `Http4sDsl#Path` at #3549.  `Uri.Path` was a mere `String` when Calvin commented.  (And my apologies for missing it!).

I'm struggling to find any that remain in the model representations.  Most of them became `List`s (common in headers) or `Query` and `Uri.Path` are built on a `Vector`.  There are some references to `Seq` in terms of derived properties, like `multiParams`, which let us change our mind later at the expense of the client being able to make assumptions.

**Comment by rossabaker** [comment] 2021-04-05 14:05
Duplicate of #1695.

**Closed by rossabaker** 2021-04-05 14:05 UTC
Labels: good first issue
