### ISSUE TITLE
Publish client for scala-js

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#956] opened 2017-02-23 03:34 UTC
Not sure that a server makes sense, but several have asked for the client.  All the libraries we need are ScalaJS capable.

**Comment by cquiroz** [comment] 2017-02-23 18:43
I've a fair amount of experience on scala.js. I could tackle this one.

**Comment by cquiroz** [comment] 2017-02-24 00:07
Checking the code I think we want to port `client` and `blaze-client` at least right?
At least `blaze-client` uses some low level connections that won't be available on scala.js. They should be rewritten to be compatible

**Comment by rossabaker** [comment] 2017-02-24 00:28
Definitely client.  I assumed blaze-client, but really, anything that can provide that Client interface is what we're really after.

I'd imagine also one of the JSON libraries.  Probably http4s-circe?

**Comment by ChristopherDavenport** [comment] 2017-02-24 01:14
Why is client non js compatible currently? We should get core client fully js compatible.

**Comment by rossabaker** [comment] 2017-02-24 01:19
Nobody has ever tried to build any of our modules for js, as far as I know.  But yeah, I think it starts at core, and bubbles up to client, and then to blaze-client or some new alternate implementation.  Follow the dependencies.

**Comment by ChristopherDavenport** [comment] 2017-02-24 01:52
I'll see if I can force client to compile to js, real quick. I think this would probably, be ...-client after core compiles to js. Then this would be a new client implementation.

**Comment by rossabaker** [comment] 2017-02-24 01:55
If it's going to be a "blaze client", then there needs to be a build of blaze on Scala JS.

**Comment by cquiroz** [comment] 2017-02-24 02:03
You can see `client` depending on `server` and then on `core` and interesting dependencies like

`scalaReflect(scalaVersion.value) % "provided"`
`fs2Io`

It will be interesting to port

**Comment by ChristopherDavenport** [comment] 2017-02-24 02:08
fs2 core is all we use ther and that is scalajs compatible. The problem is reflect which is used for inhaled parboiled and I'm unsure if that can be done. Without which our parsing has difficulties.

**Comment by rossabaker** [comment] 2017-02-24 02:13
Client only depends on server (and dsl) for testing.  DSL should be fine, but that server will need to be untangled somehow.

fs2-io is used in core.  Does that not have a JS equivalent?

parboiled2 is ported to scala.js, but our inhalation of it is not.  That's going to be needed to get core going.

**Comment by cquiroz** [comment] 2017-02-24 02:15
`fs2-io` doesn't have a .js equivalent because it uses `File` and `nio`

**Comment by rossabaker** [comment] 2017-02-24 02:16
I think in that case we'll need to split out the entity encoders, Static File, etc. that depend on that, via the jvm/js/shared structure seen in other projects.

**Comment by cquiroz** [comment] 2017-05-04 18:25
What's the state here? I could start porting core, etc but wanted to check first if there was some work already done

**Comment by rossabaker** [comment] 2017-05-04 20:19
I don't think anybody is working on this yet.

What is the strategy for tests?  Specs2 doesn't yet have a JS port, and moving to ScalaTest would be a big effort.

**Comment by cquiroz** [comment] 2017-05-04 20:43
That's a good question, I don't have an answer I normally use ScalaTest

**Comment by rossabaker** [comment] 2017-05-06 04:08
Specs2 for scala.js is [in progress](https://github.com/etorreborre/specs2/issues/465)

I think we could start working on the build now.  For now, we'll have Specs2 tests on the JVM.  In the best case, Specs2 will be ready and we can upgrade.  In the worst case, we can look at porting to ScalaTest.

**Comment by cquiroz** [comment] 2017-05-30 00:42
This is progressing but very slowly. I found a bug in cats that needs to be solved before https://github.com/typelevel/cats/issues/1708 we can proceed.

Tests would be really good since some errors don't reveal until you run the code in a js VM

**Comment by cquiroz** [comment] 2017-06-23 02:20
at the moment I'm stuck with three dependencies that don't have scala.js support for `core`

* `org.http4s:http4s-websocket`: This could probably be solvable by moving some of the code to another module
* `co.fs2:fs2-io`: This affects some decoders, I think they could be moved to another module too
* `org.log4s:log4s`: This maybe harder because it is used on some of the important classes like `StreamApp` and `threads`. One option would be to try to port `log4s` to scala.js or to replace it by a library that supports both already

What do you think? Should I split the modules and does it make sense to port or replace `log4s`?

**Comment by rossabaker** [comment] 2017-06-24 04:02
fs2-io could probably be worked around by putting those dependencies into the `scalaJVM` folder, and having blank equivalents in `scalaJS`.  Companion objects that provide instances could extend an `IoInstances` trait from each.

I think it doesn't hurt to inquire with the log4s project about whether they're willing or able to support a scala.js port.  The library has been good to us in terms of not breaking compatibility and doing one thing and one thing well.

http4s-websocket exists as a standalone project because both blaze and http4s need it.  If blaze isn't going to support websockets anymore (0.13), then this functionality could be subsumed into an http4s module.  Either way, it's work that we control and has to be done for this port.

**Comment by cquiroz** [comment] 2017-08-28 16:01
I've been slowly progressing on this and got core ported but I'm stuck porting `testing`. In there we use `Task`'s functions like `unsafeRun` and `unsafeAttemptRun` which are not available on .js. I'm not sure the exact reason but I assume it is due to JS being single threaded.

Compare
https://github.com/functional-streams-for-scala/fs2/blob/series/0.9/core/jvm/src/main/scala/fs2/TaskPlatform.scala
and
https://github.com/functional-streams-for-scala/fs2/blob/series/0.9/core/js/src/main/scala/fs2/TaskPlatform.scala

I'm not sure how to proceed from here short of trying to implement these myself

An alternative would be to go directly to the fs2-0.10 branch and avoid Task altogether

any suggestions?

**Comment by rossabaker** [comment] 2017-08-28 16:45
Are you using specs2-4.0 for the ScalaJS support?

Yeah, I think I'd target master with this.  0.17.x is already in release candidate stage.  I guess we _could_ do a backport later on, but I think master should be where all the interesting stuff is happening at this point.

How big is the diff?  We've been talking about introducing scalafmt, but that's going to suck for you if this is a big change.  We should time that with any interesting work that's in flight against master.

**Comment by cquiroz** [comment] 2017-08-28 16:50
i'm targeting master already. is master now on fs2-0.10/cats-effect?

Good suggestion about specs2

**Comment by cquiroz** [comment] 2017-08-28 16:51
The diff isn't very small but it moves classes around to some extent

**Comment by rossabaker** [comment] 2017-08-28 17:14
Yes, master is now on cats-effect.  specs2 has a RC that introduces scala.js support.

**Comment by cquiroz** [comment] 2017-08-28 17:15
ok, i guess it makes sense to rebase to master. i'll do that and try to get a WIP PR to keep track

**Comment by cquiroz** [comment] 2017-08-28 22:07
It seems the changes to master are already big enough to start from scratch. It will go much faster this time around. If so then I could wait for the scalafmt event if it is going to happen soon

**Comment by cquiroz** [comment] 2017-10-12 00:39
i found a couple of problems attempting to run the tests on scala.js. These are linking errors and are not detected on compilation due to the way `scala.js` compiles but fail nonetheless on linking/running. They maybe complicated to fix so I'm letting you know to gather opinions on these two. There maybe others lurking around

* use of `TrieMap` in a few places including:
https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Method.scala#L58
https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/util/Registry.scala#L28

Scala.js  doesn't support `TrieMap` but we could probably workaround by using the `mutable.Map` interface and using different implementations for each platform

* Use of reflection:
This is more complex to fix. Reflection is used here
https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala#L112

Reflection is a no-go on `scala.js` but I have no clue on how to workaround on this case. It would require a relatively big refactoring to have a static list of parsing methods. Any ideas?

**Comment by rossabaker** [comment] 2017-10-12 03:36
I think all of those are bad and should be fixed in core, even on the JVM:

* `Registry` is a mutable construct inherited from Spray and needs to go away.
* `Method` uses it similarly.
* There is no reason we need to use reflection other than to avoid boilerplate in header parsing.

**Comment by cquiroz** [comment] 2017-10-12 12:15
I certainly agree. I'm happy to send PRs to fix those on master

**Comment by bpholt** [comment] 2018-04-23 20:04
@cquiroz what's the status of this? Is there anything I can try to help with?

**Comment by cquiroz** [comment] 2018-04-23 20:52
Hi, i’ll try rebasing the old branch and reopen the Pr soon. Then we can identify what’s missing in core and client. the other big task is implementing a client on scala.

**Comment by matthughes** [comment] 2018-07-06 16:16
Is help wanted here?  I'd love to see this.

**Comment by cquiroz** [comment] 2018-07-06 16:21
it is certainly a work in progress. The first attempts are not very promising on js size which makes some sense as we are importing a bunch of stuff. More experimentation is needed

**Comment by matthughes** [comment] 2018-07-06 16:31
Yeah I'm sure.  I'd love to just see some of the datatypes Method, StatusCode, Uri ported.  If you get the rebased PR posted, I'd love to take a look and see if I can't help out in some way.

**Comment by cquiroz** [comment] 2018-07-06 16:33
Right, I need to do a rebase on master as i've been patching things here and there but some of those are fixed in master. i also need to update the scala.js version to include some fixes in upstream

**Comment by ChristopherDavenport** [comment] 2018-07-06 16:34
Would be a good idea perhaps to make that a topic branch in the main repo so others can contribute work.

**Comment by cquiroz** [comment] 2018-07-06 16:34
What`s a topic branch?

**Comment by ChristopherDavenport** [comment] 2018-07-06 16:35
Which branch is the one your currently using in your repo. Its just a branch in the main repo. Nothing fancy. Like `topic/scalajs`

**Comment by cquiroz** [comment] 2018-07-06 17:16
we could do that after a proper rebase, which is a bit hard as the branches have diverged

**Comment by BenHutchisonSeek** [comment] 2019-10-30 00:01
This issue has gone a bit quiet... @cquiroz where did you get to with this? 

From a look around [this branch](https://github.com/cquiroz/http4s/tree/scala.js) seems to be the most progressed version.

I'd like to see this feature completed and are willing to take over the work if a volunteer is needed.

**Comment by cquiroz** [comment] 2019-10-30 00:09
I haven’t kept it up to date, but regardless there were a few spots that created troubles, in particular related to the use of reflection, a first step would be to resend with master

**Comment by ChristopherDavenport** [comment] 2021-03-03 15:58
Fairly Certain that this is now possible because of the lack of reflection. Its a non-trivial amount of work to accomplish, but I don't think there are any massive blockers to it now.

**Comment by rossabaker** [comment] 2021-03-03 16:18
Would this be a 1.0 feature?  It hits core, which is mostly the same between 0.22 and 1.0, and it's beneficial it stays that way. 
 But CE3 is likely to be widely adopted before anyone gets too serious about this?

**Comment by ChristopherDavenport** [comment] 2021-03-10 16:38
I would expect it to be a 1.0 feature. Probably in a satellite. But we'd want core/client/circe at a minimum in the main library to all cross-compile to js.

**Comment by armanbilge** [comment] 2021-06-25 07:35
I hope nobody minds, I gave this a shot #4938  😅

**Closed** 2021-08-29 02:30 UTC
Labels: enhancement, module:core
