### ISSUE TITLE
Path DSL and unicode arrows

### ISSUE THREAD

**Issue by Unisay** [http4s/http4s#702] opened 2016-09-02 14:35 UTC
Its possible to configure Intellij Idea to replace arrows made of symbols with corresponding unicode symbols, so that typing => produces ⇒ and -> produces →

So far I had no problems with it, but today I made a route:
```scala
HttpService { case POST → Root / "test" ⇒ Ok()  }
```
Compiler said:
```
Error:(23, 34) constructor cannot be instantiated to expected type;
 found   : org.http4s.dsl./
 required: org.http4s.Request
```
after that
```
Error:(23, 14) not found: value →
    case GET → Root / test" ⇒
```

It turned out that →is not defined in the DSL, but -> is:
```scala
object -> {
  /**
   * HttpMethod extractor:
   * {{{
   *   (request.method, Path(request.path)) match {
   *     case Method.GET -> Root / "test.json" => ...
   * }}}
   */
  def unapply(req: Request): Option[(Method, Path)] = {
    Some((req.method, Path(req.pathInfo)))
  }
}
```

**Comment by Unisay** [comment] 2016-09-02 14:36
By the way, scala library does it like this:
```scala
  implicit final class ArrowAssoc[A](private val self: A) extends AnyVal {
    @inline def -> [B](y: B): Tuple2[A, B] = Tuple2(self, y)
    def →[B](y: B): Tuple2[A, B] = ->(y)
  }
```

**Comment by refried** [comment] 2016-09-02 14:40
As someone who has raised this issue in the past (#427), I now recommend using a ligature-enabled font like https://github.com/tonsky/FiraCode which will then display the two-character `->` symbol as an arrow, rather than using the Unicode.  The latest IntelliJ IDEA has great support for ligatures.

**Comment by refried** [comment] 2016-09-02 14:44
Duplicate of #427

**Closed by refried** 2016-09-02 14:44 UTC

**Comment by rossabaker** [comment] 2016-09-02 14:47
I just switched to FiraCode in Emacs.  ASCII methods and ligature renderings is the best of both worlds.
