### ISSUE TITLE
Docs site for 1.0 has no CSS

### ISSUE THREAD

**Issue by dylemma** [http4s/http4s#5067] opened 2021-08-12 21:10 UTC
The docs site at https://http4s.org/v1.0/ currently looks like this:

![image](https://user-images.githubusercontent.com/1355958/129270104-22fdc524-7a3a-4a28-9d0f-ece6b3074402.png)

Looks like all of the CSS is attempting to load from localhost instead of the actual http4s.org domain
![image](https://user-images.githubusercontent.com/1355958/129270246-e2d0e2f6-bf70-4ad3-804b-26aaa9169189.png)

**Comment by rossabaker** [comment] 2021-08-12 21:12
Thanks for reporting.  I think this is a duplicate of #4960, which I thought would be resolved when we published the 1.0.0-M24 milestone.  Drat.

**Closed by rossabaker** 2021-08-12 21:12 UTC
Labels: docs

**Comment by dylemma** [comment] 2021-08-12 21:13
Ah whoops that didn't come up in my search. Thanks for the confirmation though!
