### ISSUE TITLE
Feature request: support conditional middleware body logging

### ISSUE THREAD

**Issue by kubukoz** [http4s/http4s#4648] opened 2021-03-26 02:52 UTC
When using e.g. the client `Logger(logBody: Boolean)` middleware, I have to go all-in or all-out - this limits the reusability of a client for multiple usecases, such as streaming files and JSON bodies in different endpoints.

It would be nice if `logBody` had a reference to the request/response (presumably as a `Message[F]` in Logger, as a `Request[F]` in RequestLogger etc.).

**Comment by kevinmeredith** [comment] 2021-03-26 03:09
> Logger(logBody: Boolean) middleware

@kubukoz [Logger#logBodyText](https://github.com/http4s/http4s/blob/series/0.22/client/src/main/scala/org/http4s/client/middleware/Logger.scala#L40-L50) exists. It does not include a reference to the request/response, however it does give you an option as to what do with the payload `String`'s.

**Comment by kubukoz** [comment] 2021-03-26 03:50
Yeah, I saw that but it won't be as easy to figure out what the body is - some heuristic would have to be applied... like how do you say "is this plaintext?"? 😅

**Comment by rossabaker** [comment] 2021-03-28 05:24
I'm going to confess I lost track of what most of these alternative versions actually do several months ago.  Pull request welcome, and it would be great if a maintainer who is using these could take a look.

**Comment by rossabaker** [comment] 2021-04-12 01:21
Duplicate of #4528.

**Closed by rossabaker** 2021-04-12 01:21 UTC
