### ISSUE TITLE
jsonOf Implementation hangs on large requests

### ISSUE THREAD

**Issue by niro-sean** [http4s/http4s#2321] opened 2018-12-20 03:34 UTC
Recently I was testing sending large payloads of (10's of thousands of lines of json), and found the CPU usage of the server to max out, and seemingly never recover. After investigation I discovered the  issue to reside in the function: 
```
private[http4s] def jawnDecoderImpl[F[_]: Sync, J: Facade](msg: Message[F]): DecodeResult[F, J] =
    DecodeResult {
      msg.body.chunks
        .parseJson(AsyncParser.SingleValue)
        .map(Either.right)
        .handleErrorWith[Either[DecodeFailure, J]] {
          case pe: ParseException =>
            Stream.emit(Left(MalformedMessageBodyFailure("Invalid JSON", Some(pe))))
          case e =>
            Stream.raiseError(e)
        }
        .compile
        .last
        .map(_.getOrElse(Left(MalformedMessageBodyFailure("Invalid JSON: empty body"))))
    }
```

which is called when `jsonDecoderAdaptive(cutoff = 100000)` is called with a cutoff > 100000.

My suspicion is that the `chunks` call is producing a chunk so large the `.parseJson` call is unable to handle (though there maybe a different underlying issue I was unable to identify).

Limiting the chunk size, i.e `msg.body.chunkLimit(Integer.MAX_VALUE)` rectified the issue, and was able to decode the entity very efficiently. Alternatively, using `jsonDecoderByteBuffer[F]` rather than the default implementation was also workable.

Any further information or insights on this issue would be appreciated, cheers.
Sean.

**Comment by rossabaker** [comment] 2018-12-22 04:15
`jsonDecoderByteBufferImpl` is faster, but buffers the entire body.  That's why it's preferred, but only up to a cutoff.  Of course, since we're building a `Json`, we're still not putting an upper bound on memory consumption.  Maybe that cutoff is too low, or even shouldn't exist.

And the `jawnDecoderImpl` definitely shouldn't hang.  That sounds like a bug.  We're upgrading both circe and jawn in #2320, and it would be interesting to see if the problem persists through that.

**Comment by rossabaker** [comment] 2021-04-06 04:11
I don't know whether this is fixed or not, but it seems easy enough to unit test.

**Comment by danicheg** [comment] 2022-12-11 18:25
I did a try to reproduce the issue by unit testing of `org.http4s.circe.CirceInstances#jsonDecoder` with ~14 Mb JSON (450K+ lines of json), and everything was fine – no hangings or something. CPU consumption was high enough, but it took about 2s to decode JSON.

```scala
test("CirceInstances.jsonDecoder shouldn't hang") {
  val source =
    Source.fromURL(getClass.getResource("/generated.json"))
  val stream =
    fs2.Stream.fromBlockingIterator[IO](source.getLines().flatMap(_.getBytes()), 512)

  val decoded =
    jsonDecoder[IO].decode(Media[IO](stream, Headers("Content-Type" -> "application/json")), true)

  assertIO(decoded.value.flatTap(_ => IO.blocking(source.close())), Either.right(Json.Null))
}
```
Seemingly something was fixed in jawn/circe. So, I close this issue. But feel free to reopen if it doesn't work for you.

**Closed by danicheg** 2022-12-11 18:25 UTC
Labels: bug, module:jawn
