### ISSUE TITLE
Flaky test: LocalTokenBucket

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2311] opened 2018-12-06 12:45 UTC
```
[info] LocalTokenBucket should
[error]   x contain initial number of tokens equal to specified capacity (1 second, 384 ms)
[error]    Timeout after 1 second (retries = 0, timeout = 1 second), timeFactor = 1 (ThrottleSpec.scala:39)
[error] org.http4s.server.middleware.ThrottleSpec$$anonfun$1$$anonfun$apply$1.apply(ThrottleSpec.scala:39)
[error] org.http4s.server.middleware.ThrottleSpec$$anonfun$1$$anonfun$apply$1.apply(ThrottleSpec.scala:18)
[info]   + add another token at specified interval when not at capacity (1 second, 449 ms)
[error]   x not add another token at specified interval when at capacity (1 second, 468 ms)
[error]    Timeout after 1 second (retries = 0, timeout = 1 second), timeFactor = 1 (ThrottleSpec.scala:79)
[error] org.http4s.server.middleware.ThrottleSpec$$anonfun$1$$anonfun$apply$10.apply(ThrottleSpec.scala:79)
[error] org.http4s.server.middleware.ThrottleSpec$$anonfun$1$$anonfun$apply$10.apply(ThrottleSpec.scala:61)
[error]   x only return a single token when only one token available and there are multiple concurrent requests (1 second, 500 ms)
[error]    Timeout after 1 second (retries = 0, timeout = 1 second), timeFactor = 1 (ThrottleSpec.scala:95)
[error] org.http4s.server.middleware.ThrottleSpec$$anonfun$1$$anonfun$apply$15.apply(ThrottleSpec.scala:95)
[error] org.http4s.server.middleware.ThrottleSpec$$anonfun$1$$anonfun$apply$15.apply(ThrottleSpec.scala:82)
```

https://travis-ci.org/http4s/http4s/jobs/464170472#L836

**Comment by m-sp** [comment] 2021-02-14 22:42
duplicate of https://github.com/http4s/http4s/issues/4386

**Closed by m-sp** 2021-02-14 22:42 UTC
Labels: testing
